### ISSUE TITLE
Unable to create Let´s Encrypt Certificates - 404 Not Found

### ISSUE THREAD

**Issue by AlexZeller** [jc21/nginx-proxy-manager#718] opened 2020-11-13 13:46 UTC
Hello everyone,

I am having issues trying to get NPM to work with Let´s Encrypt certificates.

**Checklist**
I am using the latest docker image (jc21/nginx-proxy-manager:latest) and the docker-compose and config.js file from the setup page (https://nginxproxymanager.com/setup/). 
I can add proxy hosts without SSL and everything works as expected. I also see the standard welcome page when no host is connected. I also checked from outside my network.

**Describe the bug**
When trying to add a Certificate I get the following error:

    Error: Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-2" --agree-tos --email "mail@domain.com" --preferred-challenges "dns,http" --domains "subdomain.domain.com" 
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator webroot, Installer None
    Obtaining a new certificate
    Performing the following challenges:
    http-01 challenge for subdomain.domain.com
    Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
    Waiting for verification...
    Challenge failed for subdomain.domain.com
    http-01 challenge for subdomain.domain.com
    Cleaning up challenges
    Some challenges have failed.

        at ChildProcess.exithandler (child_process.js:308:12)
        at ChildProcess.emit (events.js:314:20)
        at maybeClose (internal/child_process.js:1051:16)

I also executed the command directly inside the container which produced this error:

    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator webroot, Installer None
    Obtaining a new certificate
    Performing the following challenges:
    http-01 challenge for subdomain.domain.com
    Using the webroot path /data/letsencrypt-acme-challenge for all unmatched domains.
    Waiting for verification...
    Challenge failed for domain subdomain.domain.com
    http-01 challenge for subdomain.domain.com
    Cleaning up challenges
    Some challenges have failed.

    IMPORTANT NOTES:
     - The following errors were reported by the server:
    Domain: subdomain.domain.com
    Type:   unauthorized
    Detail: Invalid response from
    http://subdomain.domain.com/.well-known/acme-challenge/PG-0cH7mIJNy8mEBseSqsI_ixF7q8rB3cwvhYmWEwoQ
    [37.157.156.27]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML
    2.0//EN\">\n<html><head>\n<title>404 Not
    Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p"

    To fix these errors, please make sure that your domain name was
    entered correctly and the DNS A/AAAA record(s) for that domain
    contain(s) the right IP address.

**To Reproduce**
I am using a fresh install. I tried the latest docker image from jlesage/nginx-proxy-manager and jc21/nginx-proxy-manager. I also tried to add the certificate when creating a host which produced an internal error.

**Additional context**
I am am using a subdomain, that has its on A Record pointing to the correct IP address. Since I can also reach the Welcome page I assume the is no problem with my DNS settings. I also tried Caddy as a reverse proxy which had no problems with the Certificates.

Also, thanks for this awesome project to all contributors 👍

**Comment by socheatsok78** [comment] 2020-11-21 03:55
I'm having a different error, been stuck in this step ever since last update

```
[11/20/2020] [7:52:07 PM] [Nginx ] › ℹ info Reloading Nginx
[11/20/2020] [7:52:08 PM] [SSL ] › ℹ info Requesting Let'sEncrypt certificates for Cert #87: -----------------
[11/20/2020] [7:52:08 PM] [Nginx ] › ℹ info Reloading Nginx
[11/20/2020] [7:52:08 PM] [Express ] › ⚠ warning Command failed: /usr/bin/certbot certonly --non-interactive --config "/etc/letsencrypt.ini" --cert-name "npm-87" --agree-tos --email "socheat@--------------" --preferred-challenges "dns,http" --domains "-------------------"

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Missing command line flag or config entry for this setting:
Please choose an account
Choices: ['2712a1------@2020-05-08T10:07:23Z (b296)', 'cf6a95------@2020-10-21T11:59:23Z (f9d4)']
```

**Comment by chaptergy** [comment] 2021-05-12 20:51
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/210

**Closed by chaptergy** 2021-05-12 20:51 UTC
Labels: bug
