### ISSUE TITLE
ACL on Proxy Host for Nginx Proxy Manager Administration Does Not Auth

### ISSUE THREAD

**Issue by Jiriteach** [jc21/nginx-proxy-manager#827] opened 2021-01-15 04:08 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? 
Yes

- Are you sure you're not using someone else's docker image? 
Yes

- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
N/A

**Describe the bug**
I have a proxy host setup to NPM administration. 
e.g. abc.domain.com --> proxy host to NPM:81. This is working fine. I would like to add an ACL with HTTP basic auth in-front of the NPM login screen. Doing so causes auth to prompt but credentials do not work on Chrome or Firefox. Seems to work on Safari.

- What version of Nginx Proxy Manager is reported on the login page?
2.7.2 (which is a bug since 2.7.3 is installed)

**To Reproduce**
1. Create a proxy host rule to NPM administration. 
2. Add an access list to the proxy host rule.
3. Test on Google Chrome or Firefox.

**Expected behavior**
Auth to success and show the NPM administration login screen.

**Operating System**
NPM is running on a RPI4 via Docker.
Browsers have been tested on both MacOS and Windows.

**Comment by NovaViper** [comment] 2021-01-27 14:07
I can confirm this issue aswell, same rasspberry pi setup. For me at least, it just keeps in locked in the authentication prompts and never lets me get to the manager

**Comment by Wilbert-Garcia** [comment] 2021-01-29 03:26
I have a simliar issue however on mobile i get through the auth pop up the first time (chrome/safari), I also can get through the first time around when using safari on mac. When using the desktop version of chrome/brave/firefox it just loops. I noticed that if i login once in the auth pop up and leave it there for lets say 5-10 mins it eventually goes through.

**Comment by vercas** [comment] 2021-01-31 02:47
I am having a similar issue. I can get past the HTTP auth prompt, but then it won't accept my username and password.  
It simply says `Unauthorized.` under the password field.

**Comment by dokbua** [comment] 2021-01-31 14:23
Just ran into this problem too.  I had to enable the port 81 again to be able to login directly and remove the acl and be able to use it again.

**Comment by parasdaryanani** [comment] 2021-04-03 19:10
Same issue on Ubuntu 20.04.

**Comment by chaptergy** [comment] 2021-05-12 22:21
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/334

**Closed by chaptergy** 2021-05-12 22:21 UTC
Labels: bug
