### ISSUE TITLE
make host number visible to find logs easily

### ISSUE THREAD

**Issue by toxic0berliner** [jc21/nginx-proxy-manager#1014] opened 2021-04-12 20:10 UTC
Maybe I'm just not good enought, but I cannot find the number assigned to a host setup easily.
I'd like to be able to easily find that out since I got quite a lot of them, and when I want to look at /data/logs/proxy_host-xx.log I never know which xx I'm looking for...

So either adding a field to name each host in the gui and use a normalized version of this name, or let me display a column "number" or # in the GUI to be able to find which host I'm after...

Thanks in advance for considering it.

**Comment by chaptergy** [comment] 2021-05-12 23:34
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/174

**Closed by chaptergy** 2021-05-12 23:34 UTC
Labels: enhancement
