### ISSUE TITLE
Custom HTML for all different Error Pages (403,404,400,....)

### ISSUE THREAD

**Issue by Secarius** [jc21/nginx-proxy-manager#870] opened 2021-02-07 13:12 UTC
**Describe the solution you'd like**
It would be very nice to be able to setup the error pages to custom html pages
It should be a "general" setting for all the proxy hosts.

**Describe alternatives you've considered**
changing them manual in the code will destroy the oportunity to update i think

**Additional context**
in the settings menu would be nice to have a option: 
example:
- add error page:
- - error numbe: 403
- - error handling:
- - - standard error page
- - - custom html
- - - rediect

**Comment by kwmc-lucas** [comment] 2021-02-26 14:17
+1

I'm looking for exactly this, when we have some downtime when updating a site I would like to present a static page for the 502 error.

**Comment by codeagencybe** [comment] 2021-03-30 09:50
any update on this? Would also like to see this feature

**Comment by Secarius** [comment] 2021-04-18 21:12
any update so far?

**Comment by chaptergy** [comment] 2021-05-12 23:08
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/26

**Closed by chaptergy** 2021-05-12 23:08 UTC
Labels: enhancement

**Comment by b4sh1t1** [comment] 2022-01-22 15:37
> Duplicate of #26

it's not duplicate; the guy in issue #26 explain how to add a custom page; not how to add a custom 502!

**Comment by kylethedeveloper** [comment] 2022-04-15 19:04
You may try my solution:
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/26#issuecomment-1100295543
