### ISSUE TITLE
Filter and Sort on Host Pages

### ISSUE THREAD

**Issue by JBM1866** [jc21/nginx-proxy-manager#1725] opened 2022-01-04 03:18 UTC
It would be amazing if you could have a filter option and a sort option added to the Host Pages.
That way if you are looking for a certain host, you can quickly do so.
It will also allow you to run a report on all backends on a certain host/port or allowed by a certain ACL.

The sort function would also be ideal to tidy up the list of hosts.

Something also to optionally show a certain number of items in the list before going to a second page (however keeping the option to show all in one list).

Also as a part of the Filter, being able to search for any item settings, ie. all those with certain HTTPS settings.

The table would be even further improved if you could change the columns shown, ie add in other options to see if you missed configuring anything on backend hosts.

Other than this, the program is GREAT! Keep up the amazing work!! :)

**Comment by JBM1866** [comment] 2022-01-04 03:18
<img width="1197" alt="Screen Shot 2022-01-04 at 2 14 39 pm" src="https://user-images.githubusercontent.com/55431579/148005135-1e9387f5-ad6e-4f4e-8f8d-90a1293b8447.png">

**Comment by chaptergy** [comment] 2022-01-04 12:52
Closing as a duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1715 and https://github.com/jc21/nginx-proxy-manager/issues/409

**Closed by chaptergy** 2022-01-04 12:52 UTC
Labels: enhancement
