### ISSUE TITLE
Forward to static site in folder on same computer

### ISSUE THREAD

**Issue by torquemada163** [jc21/nginx-proxy-manager#786] opened 2020-12-21 17:56 UTC
Can I configure NPM to redirect my domain name to a folder with static HTML files on the same host as the NPM containers?
If this is possible, how?

Thanks!

**Comment by eyduh** [comment] 2020-12-23 15:02
I'm no docker nor webdev pro myself but I would guess that you could serve the static html files with some webserver, like nginx or lighttpd (outside of docker) on a non-standard port then use nginx-proxy-manager to redirect to 127.0.0.1:PORT or possibly serverhostname:PORT

I'll be trying something similar in the next few weeks and will report back if I manage to get it to work. c:

**Comment by torquemada163** [comment] 2020-12-24 12:56
I don't want to have multiple Nginx instances on the same machine....... I would like to get by with one, if possible...

**Comment by kellcomnet2** [comment] 2021-01-01 14:26
Duplicate of #280

**Comment by chaptergy** [comment] 2021-05-12 21:49
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/58

**Closed by chaptergy** 2021-05-12 21:49 UTC
Labels: product-support
