### ISSUE TITLE
WEB-UI HTTPS support

### ISSUE THREAD

**Issue by Kopernikus1979** [jc21/nginx-proxy-manager#1361] opened 2021-08-29 11:50 UTC
Hi,

Would it be possible to integrate direct HTTPS for the Web-UI?
Now I create a reverse proxy for this purpose, but it would be better if we can access it directly.
Like this: https://IP:81

**Comment by chaptergy** [comment] 2021-08-29 14:03
This comes with many issues as the domain or the IP address could be anything. So it is not possible to issue a valid certificate for this. And as browsers tighten the security more and more on I valid certificates, this might prevent some people from accessing the admin panel at all. So the officially preferred method is via a proxy host.

This is also a duplicate of https://github.com/jc21/nginx-proxy-manager/issues/182

**Closed by chaptergy** 2021-08-29 14:03 UTC
Labels: enhancement
