### ISSUE TITLE
Custom SSL GUI Button not working

### ISSUE THREAD

**Issue by rrw357719** [jc21/nginx-proxy-manager#1707] opened 2021-12-30 16:13 UTC
Attempting to add custom ssl certificate when the button is clicked on the gui the additional window does not open prompting for certificates. I have confirmed that the lets encrypt window opens as expected. Is there a work around for this bug?

**Comment by chaptergy** [comment] 2021-12-30 16:56
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1676

**Comment by chaptergy** [comment] 2021-12-30 16:57
The workaround is using image tag `:github-pr-1677` until the next release comes

**Closed by chaptergy** 2021-12-30 16:56 UTC
