### ISSUE TITLE
Logs view in Web UI

### ISSUE THREAD

**Issue by jeremy-chua** [jc21/nginx-proxy-manager#1116] opened 2021-05-22 06:31 UTC
First of all, thanks for this great software. Deploying and configuring a proxy had never been so easy.
It took me less than 5mins from deployment, setting up host to SSL configuration.

It will be a nice feature to have logs view in each host. It will make debugging much much more smooth. I agree it is a good to have feature.

In addition, we can have the syslog server configuration. This will help in SIEM integration.

**Comment by jeremy-chua** [comment] 2021-05-22 06:33
My request is similar to [https://github.com/jc21/nginx-proxy-manager/issues/1103](url)

**Comment by chaptergy** [comment] 2021-05-22 07:19
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/401

**Closed by chaptergy** 2021-05-22 07:19 UTC
Labels: enhancement
