### ISSUE TITLE
Support for load balancing

### ISSUE THREAD

**Issue by stather** [jc21/nginx-proxy-manager#1596] opened 2021-11-18 18:44 UTC
It doesn't seem possible to specify load balancing options. It would be really useful if multiple forward hosts could be specified along with the load balancing option, e.g. least_conn.

**Comment by chaptergy** [comment] 2021-11-18 18:47
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/156

**Closed by chaptergy** 2021-11-18 18:47 UTC
Labels: enhancement
