### ISSUE TITLE
Support for GoDaddy Let'e Encrypt DNS challenge

### ISSUE THREAD

**Issue by jeremy-chua** [jc21/nginx-proxy-manager#1032] opened 2021-04-22 02:04 UTC
First of all, thanks for the great work!

Let's Encrypt Wildcard cert requires DNS challenge, will be great if GoDaddy is included in the list.

**Comment by chaptergy** [comment] 2021-05-09 17:07
Unfortunately this requires a certbot DNS plugin to exist for this provider. Though there was [some progress made](https://github.com/certbot/certbot/pull/6135) to create such a plugin, no one seems to have actually [published a plugin like this](https://pypi.org/search/?q=certbot+godaddy).

If anyone is interested in publishing a plugin for GoDaddy, [this netcup plugin](https://github.com/coldfix/certbot-dns-netcup/blob/master/certbot_dns_netcup.py) can serve as inspiration.

**Comment by chaptergy** [comment] 2021-05-09 17:48
Also: duplicate of https://github.com/jc21/nginx-proxy-manager/issues/863

**Comment by chaptergy** [comment] 2021-05-18 18:48
Closed via https://github.com/jc21/nginx-proxy-manager/pull/1095

**Closed by chaptergy** 2021-05-18 18:48 UTC
Labels: enhancement
