### ISSUE TITLE
Error with DNS challenge for OVH

### ISSUE THREAD

**Issue by TheFlatline** [jc21/nginx-proxy-manager#1113] opened 2021-05-21 10:04 UTC
**Describe the bug**
While trying to add SSL certificates using DNS and OVH it fails with message:
`ERROR:certbot._internal.log:TypeError: create_record() got an unexpected keyword argument 'type'`

A quick fix (saw in https://stackoverflow.com/questions/67536198/got-an-error-while-trying-to-create-ssl-certificate-on-ovh-vps-server) was to change "type" to "rtype" in the lines
`self.provider.create_record(type='TXT', name=record_name, content=record_content)`
and
`self.provider.delete_record(type='TXT', name=record_name, content=record_content)`

inside the file:

`/opt/certbot/lib64/python3.7/site-packages/certbot/plugins/dns_common_lexicon.py`

inside the container.

**Comment by chaptergy** [comment] 2021-05-21 13:44
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1092. we'll have to wait for a new version of certbot. Then you'll have to either recreate the docker container or connect into it and manually update certbot.

**Closed by chaptergy** 2021-05-21 13:44 UTC
Labels: bug
