### ISSUE TITLE
force https for the npm ui

### ISSUE THREAD

**Issue by Matthias-Hermsdorf** [jc21/nginx-proxy-manager#1463] opened 2021-10-05 17:22 UTC
To use an userinterface on http to give other services https is a bit odd.

Recommend to use a extra domain for the ui. If the domain is present, force the use this domain with https and prohibit the the serverip:81 path.

Toggling the ui via the docker-compose.yml would be nice to. This configuration will be readonly most ot the time.

btw: npm is set for node package manager. It is a bad decision to use it for another piece of software.

**Comment by chaptergy** [comment] 2021-10-05 17:57
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/182

**Closed by chaptergy** 2021-10-05 17:57 UTC
Labels: enhancement
