### ISSUE TITLE
How to use Custom Nginx Configuration

### ISSUE THREAD

**Issue by jegged** [jc21/nginx-proxy-manager#172] opened 2019-07-23 08:37 UTC
is there any examples to show how to use "Custom Nginx Configuration" 
![批注 2019-07-23 163436](https://user-images.githubusercontent.com/5977574/61696549-22967300-ad68-11e9-8120-e5cf2f501818.png)

**Comment by jc21** [comment] 2019-07-23 22:28
No there isn't. It's a feature that's been added for advanced users with previous nginx knowledge. If you tell me what you're trying to achieve, I can give you a specific example.

**Comment by RCFilm** [comment] 2019-07-24 16:48
Sorry to highjack this thread but, I have a similar question.

I am trying to have nxgin do a re-right of the url every time.

the problem is one of my site behind the reverse proxy is set for'
(http://example.com:8080/) & (https://example.com:8443/). its a unifi controller and i can change the port to 80 and 443 without the service failing. so i just forwarded 8443 and 8080 to 80 and 443 but i really need it to perform a re-right as well every time to fix the issue.

So i need nxgin to change the http://example.com:8080 & https://example.com:8443/) to just https://example.com.

Any help would be great.

**Comment by RCFilm** [comment] 2019-07-24 20:11
I just can seem to use a standard Nxgin Rewrite.
I used this but it did not work.

server {
    listen 8080;
    listen 80;
    listen 8443 ssl;
    listen 443 ssl;
    server_name www.old-name.com old-name.com;
    return 301 $scheme://www.new-name.com$request_uri;
}

**Comment by businesslogic360** [comment] 2019-07-26 09:29
Hi, How can I use the same domain name with different ports? ID I want to add a new port the app shows that the domain is already in use.

**Comment by Wadera** [comment] 2019-09-03 09:54
Anyone know how to allow access to the network only from internal network?

I've tried something like:

`location / {
    allow 88.99.255.123;
    allow 192.168.0.1/15;
    allow 172.0.0.1/8;
    deny all;
}`

Where `172.0.0.1/8` is my Docker subnet (including OpenVPN), `192.168.0.1/15` is for my local behind NAT networks for home PC, Netbooks etc. Unfortunately -  when I apply this config - I've got: `404 Not Found` error :(

**Comment by Wadera** [comment] 2019-09-03 11:28
For any interested. I've just dropped header and footer. 

My current **Custom Nginx Configuration** in Advanced tab is:

```
allow 88.99.123.123
allow 192.168.0.1/15;
allow 172.0.0.1/8;
deny all;
``` 

where `88.99.123.123` is my external IP address. 

This solve my issue. Host is accessible only from local / VPN network.

**Comment by aymenSo** [comment] 2020-02-17 15:43
Anyone was able o configure seafile server over nginx-proxy-manager?
nginx configuration for seafile is in the following link:
https://seafile.readthedocs.io/en/latest/config/nginx/
I am trying without success!

**Comment by geoffrothman** [comment] 2021-01-20 04:50
> For any interested. I've just dropped header and footer.
> 
> My current **Custom Nginx Configuration** in Advanced tab is:
> 
> ```
> allow 88.99.123.123
> allow 192.168.0.1/15;
> allow 172.0.0.1/8;
> deny all;
> ```
> 
> where `88.99.123.123` is my external IP address.
> 
> This solve my issue. Host is accessible only from local / VPN network.

I'm assuming you had a semicolon at the end of the first line right?

**Comment by Wadera** [comment] 2021-01-20 14:18
Correct - fixed on comment ;)

**Comment by chaptergy** [comment] 2021-05-10 23:09
This issue has gone a little off the rails. I'll close this for now. If you have a specific question, please open a separate issue for this.

**Closed by chaptergy** 2021-05-10 23:09 UTC
Labels: enhancement

**Comment by SteveGBuck** [comment] 2021-06-10 13:37
> Sorry to highjack this thread but, I have a similar question.
> 
> I am trying to have nxgin do a Rewrite of the URL every time.
> 
> the problem is one of my site behind the reverse proxy is set for'
> (http://example.com:8080/) & (https://example.com:8443/). it's an unifi controller and I can change the port to 80 and 443 without the service failing. so I just forwarded 8443 and 8080 to 80 and 443 but I really need it to perform a Rewrite as well every time to fix the issue.
> 
> So I need nxgin to change the http://example.com:8080 & https://example.com:8443/) to just https://example.com.
> 
> Any help would be great.

Did you solve this?  I too am setting up unifi controller in Docker behind NPM proxy and unsure how I might have all the required ports handled by the proxy.

I have a proxy host setup in NPM:

unifi.mydomain.com > https://container_name:8443

This works great for the web interface (and because its SSL end to end there's no issue with the login error).

But I also need to redirect the following ports to the container too:

8080/tcp - Device command/control

8880/tcp - HTTP portal

3478/udp - STUN service

6789/tcp - Speed Test (unifi5 only)

I could just map the ports to the docker host instead of just expose.  Or use "streams" in NPM but this uses IP address only which could change on my container.

**Comment by gaozhidf** [comment] 2021-12-17 09:38
nginx-proxy-manager uses `advanced_config ` as `Custom Nginx Configuration`,
https://github.com/jc21/nginx-proxy-manager/blob/e91019feb91ca29187dbc106b96d5becda5679b1/backend/templates/proxy_host.conf

**Comment by marlonleite** [comment] 2023-09-20 11:19
hi, Does someone know how to change the return ssl conf to port 308 instead of default 301?
 When I try to use nginx with ssl to APIs, POST redirect to GET. :/
