### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by Kaczuc** [jc21/nginx-proxy-manager#1629] opened 2021-12-03 20:15 UTC
When you try to log in and enter your access data correctly, you are not redirected to the panel
This happens when I add a proxy for him

**Comment by chaptergy** [comment] 2021-12-03 20:17
You really need to provide more information. See https://github.com/jc21/nginx-proxy-manager/issues/1271, sections _For any error_ and _NPM admin page is staying blank or behaving weirdly_.

**Comment by Kaczuc** [comment] 2021-12-03 20:20
So I added a reverse proxy for the software itself and then I am not able to log in using the subdomain only using the ip address: port I am able to do this

**Comment by chaptergy** [comment] 2021-12-03 20:24
This is still not enough to start debugging this problem, as it is not reproducible. Please provide logs:

**See #1271, sections _For any error_ and _NPM admin page is staying blank or behaving weirdly_.**

Showing how you set up the reverse proxy might also help.

**Comment by Kaczuc** [comment] 2021-12-03 20:29
So this is my configuration for web panel nginx 
https://screenshot.zaq1wsx.ovh/i/807up.png
https://screenshot.zaq1wsx.ovh/i/2qred.png
I'm just usting clouflare
After I try login page only reload and back to login arena

**Comment by Kaczuc** [comment] 2021-12-03 20:31
So this is my configuration for web panel nginx proxy manger I using cloudflare for SSL. After I try login to admin dashboard using my subdomain page only reload and back to login arena
https://screenshot.zaq1wsx.ovh/i/8ms5o.png

**Comment by chaptergy** [comment] 2021-12-03 20:36
Please, just provide some logs, I can't help you otherwise 

:point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down::point_down:  
> **See #1271, sections _For any error_ and _NPM admin page is staying blank or behaving weirdly_.**  

:point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up::point_up:

**Comment by Kaczuc** [comment] 2021-12-03 20:37
`[12/3/2021] [8:13:56 PM] [Global   ] › ℹ  info      No valid environment variables for database provided, using default SQLite file '/data/database.sqlite'
[12/3/2021] [8:13:56 PM] [Global   ] › ℹ  info      Generating SQLite knex configuration
[12/3/2021] [8:13:56 PM] [Global   ] › ⬤  debug     Wrote db configuration to config file: ./config/production.json
[12/3/2021] [8:13:56 PM] [Migrate  ] › ℹ  info      Current database version: none
[12/3/2021] [8:13:56 PM] [Setup    ] › ℹ  info      Creating a new JWT key pair...
[12/3/2021] [8:14:04 PM] [Setup    ] › ℹ  info      Wrote JWT key pair to config file: /app/config/production.json
[12/3/2021] [8:14:04 PM] [Setup    ] › ℹ  info      Logrotate Timer initialized
[12/3/2021] [8:14:04 PM] [Setup    ] › ℹ  info      Logrotate completed.
[12/3/2021] [8:14:04 PM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[12/3/2021] [8:14:04 PM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[12/3/2021] [8:14:04 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[12/3/2021] [8:14:04 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[12/3/2021] [8:14:05 PM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
[12/3/2021] [8:14:05 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/3/2021] [8:14:05 PM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[12/3/2021] [8:14:05 PM] [Global   ] › ℹ  info      Backend PID 237 listening on port 3000 ...
[12/3/2021] [8:14:05 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:14:05 PM] [SSL      ] › ℹ  info      Renew Complete
`QueryBuilder#allowEager` method is deprecated. You should use `allowGraph` instead. `allowEager` method will be removed in 3.0
`QueryBuilder#eager` method is deprecated. You should use the `withGraphFetched` method instead. `eager` method will be removed in 3.0
QueryBuilder#omit is deprecated. This method will be removed in version 3.0
Model#$omit is deprected and will be removed in 3.0.
[12/3/2021] [8:17:06 PM] [Nginx    ] › ℹ  info      Reloading Nginx
Duplicate relation "access_list" in a relation expression. You should use "a.[b, c]" instead of "[a.b, a.c]". This will cause an error in objection 2.0
[12/3/2021] [8:17:34 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:20:45 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:21:01 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:21:30 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:21:56 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:24:37 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:27:53 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:32:20 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:32:47 PM] [Access   ] › ℹ  info      Building Access file #1 for: [domain]
[12/3/2021] [8:32:47 PM] [Access   ] › ℹ  info      Adding: admin
[12/3/2021] [8:32:47 PM] [Access   ] › ✔  success   Built Access file #1 for: [domain]
[12/3/2021] [8:32:57 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:32:57 PM] [Access   ] › ℹ  info      Building Access file #1 for: https://[domain]/
[12/3/2021] [8:32:57 PM] [Access   ] › ℹ  info      Adding: admin
[12/3/2021] [8:32:57 PM] [Access   ] › ✔  success   Built Access file #1 for: https://[domain]/
[12/3/2021] [8:33:11 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:33:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:33:33 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/3/2021] [8:36:08 PM] [Nginx    ] › ℹ  info      Reloading Nginx`

**Comment by Kaczuc** [comment] 2021-12-03 20:39
![image](https://user-images.githubusercontent.com/43011737/144669833-f77f03c8-a526-4561-9073-4a21bd9be85f.png)
In web console I don't have any error

**Comment by Kaczuc** [comment] 2021-12-03 20:46
![image](https://user-images.githubusercontent.com/43011737/144670517-72ffeedb-a942-494d-ad26-b8a6a743c662.png)
it looks like this when using a subdomain for nginx resolve proxy

**Comment by chaptergy** [comment] 2021-12-03 20:51
Allright, is your system clock correct? It might be that the access token expires instantly due to an incorrect system clock.  
Otherwise please open the "network" tab in your web console, and check the "Preserve log" checkmark (1). Try to log in again. After your issue occurred, click the download button (2) to download it as a har file. Then please provide this file to me. Since this file contains sensitive information (the domain name, your username and your password), you should upload it to a file hoster where the file expires after a short period of time like [file.io](https://www.file.io/) where the file is deleted after a single download.

![image](https://user-images.githubusercontent.com/26956711/144670721-79e05c64-5fb7-4b97-95d9-1c621aef2311.png)

**Comment by Kaczuc** [comment] 2021-12-03 20:55
https://file.io/LFSQEQely7uC and yes, I have the current date and time

**Comment by chaptergy** [comment] 2021-12-03 21:03
Hm, were there really only two requests for the font files? The file you provided does not contain any more. The second file you provided after updating your comment was deleted before I could even download it.

**Comment by Kaczuc** [comment] 2021-12-03 21:05
Oh sorry, I think I accidentally downloaded it already adds a new link I covered my e-mail address and password in the document
https://file.io/1RNypmRsRO4q

**Comment by chaptergy** [comment] 2021-12-03 21:10
It seems you are using cloudflare, have you tried disabling cloudflare and see if that fixes it?

**Comment by Kaczuc** [comment] 2021-12-03 21:18
I will try it immediately, however, when I turn off cloudflare, the subdomain does not correspond to what I should have A or CNAME record?

**Comment by chaptergy** [comment] 2021-12-03 21:21
I don't understand what you are trying to ask. Are you asking whether you should put the IP address of your npm instance in an A or CNAME record? It should be an A record, CNAME is only for an alias if you have a different domain already pointing to your npm instance.

**Comment by Kaczuc** [comment] 2021-12-03 21:28
So I turned off cloudflare and apply SSL let's encrypt but still having this problem I can't completely remove SSL because I have
![image](https://user-images.githubusercontent.com/43011737/144675062-a7997817-7bfd-41c6-b9b6-1e08605bf783.png)

**Comment by Kaczuc** [comment] 2021-12-03 21:39
In google chrome private mode, my login was fine after disconnecting cloudflare

**Comment by chaptergy** [comment] 2021-12-03 21:41
Then unfortunately I don't really know what the issue could be then, your network logs do look really weird but mostly due to cloudflare stuff. But nothing other I could put my finger on.  
But if it seems to work in a private tab with cloudflare disabled, then cloudflare might well be the issue and the browser has cached something which causes it to still not work in non-private tabs

**Comment by Kaczuc** [comment] 2021-12-03 21:43
I'll try to wait some time and let you know if it helped at all

**Comment by Kaczuc** [comment] 2021-12-03 21:47
Hmm, I think I know what it may be, most likely it is because I have a roboform installed that remembers passwords and logs in to websites by myself.

**Comment by Kaczuc** [comment] 2021-12-04 13:43
It looks like the problem is on my side and it's about google chrome on a clean install in a virtual machine no problem

**Comment by chaptergy** [comment] 2021-12-04 14:28
Good to know, then I will go ahead and close this issue.

**Closed by chaptergy** 2021-12-04 14:28 UTC
Labels: bug
