### ISSUE TITLE
Request Feature to Integrate with Oauth2 or Azure Active Directory Authentication

### ISSUE THREAD

**Issue by mohali-id** [jc21/nginx-proxy-manager#1617] opened 2021-11-30 09:42 UTC
Please added feature to authenticate user with Oauth2 or Azure Active Directory Authentication

**Comment by chaptergy** [comment] 2021-11-30 09:44
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/69

**Closed by chaptergy** 2021-11-30 09:44 UTC
Labels: enhancement
