### ISSUE TITLE
Install bug on RPi4 version 2.9.3

### ISSUE THREAD

**Issue by ACNiC03** [jc21/nginx-proxy-manager#1121] opened 2021-05-24 23:43 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - No
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
NPM container is unhealthy, i will put the logs under this bug. Also Bad Gateway when trying to log in

**Nginx Proxy Manager Version**
2.9.3

**To Reproduce**

install steps:
```commandline
sudo -i
mkdir NginxProxyManager
cd NginxProxyManager
nano docker-compose.yml
```

inside file:
```yml
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "<OWN NAME>"
      DB_MYSQL_PASSWORD: "<SAME AS MYSQL_PASSWORD>"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data/nginx-proxy-manager:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: ghcr.io/linuxserver/mariadb
    restart: unless-stopped
    environment:
      PUID: 1001
      PGID: 1001
      TZ: "Europe/Amsterdam"
      MYSQL_ROOT_PASSWORD: "<OWN ROOT PASSWORD (WITHOUT SPECIAL CHARACTERS)"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "<OWN NAME>"
      MYSQL_PASSWORD: "<RANDOM PASSWORD>"
    volumes:
      - ./data/mariadb:/config
```

**Expected behavior**
healthy container and no bad gateway at login page

**Screenshots**
![image](https://user-images.githubusercontent.com/64742934/119418661-c8b2bb80-bcf8-11eb-804c-0888adf2d675.png)
![image](https://user-images.githubusercontent.com/64742934/119418740-f992f080-bcf8-11eb-8600-7b8975034a8d.png)

**Operating System**
RPi4 With Portainer installed. RaspberryPi_OS NPM installed on CLI

**NOTE**
In the bug it says "migrate" or something, this is a fresh install of NPM. I tried same steps on a different clean installed RPi4 and the same thing is happening

**Additional context**
<details><summary>Logs</summary>

```
2021-05-24T23:30:30.747862448Z [5/24/2021] [11:30:30 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:30.777961760Z [5/24/2021] [11:30:30 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:30.782063918Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:30.782290304Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:30.798007239Z [5/24/2021] [11:30:30 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:31.807597987Z [5/24/2021] [11:30:31 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:31.826436091Z [5/24/2021] [11:30:31 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:31.829137412Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:31.829215523Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:31.841819437Z [5/24/2021] [11:30:31 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:32.858710365Z [5/24/2021] [11:30:32 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:32.887535857Z [5/24/2021] [11:30:32 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:32.891593515Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:32.891702255Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:32.901896789Z [5/24/2021] [11:30:32 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:33.918597851Z [5/24/2021] [11:30:33 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:34.093249547Z [5/24/2021] [11:30:34 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:34.099524847Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:34.099627031Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:34.229717429Z [5/24/2021] [11:30:34 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:35.242891292Z [5/24/2021] [11:30:35 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:35.273441988Z [5/24/2021] [11:30:35 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:35.278074918Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:35.278260749Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:35.288441283Z [5/24/2021] [11:30:35 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:36.305199238Z [5/24/2021] [11:30:36 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:36.338187759Z [5/24/2021] [11:30:36 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:36.344212951Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:36.344442041Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:36.354411929Z [5/24/2021] [11:30:36 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:37.362241672Z [5/24/2021] [11:30:37 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:37.378636007Z [5/24/2021] [11:30:37 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:37.380911352Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:37.380992685Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:37.392373021Z [5/24/2021] [11:30:37 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:38.409647067Z [5/24/2021] [11:30:38 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:38.442922640Z [5/24/2021] [11:30:38 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:38.446628784Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:38.446717376Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:38.455254003Z [5/24/2021] [11:30:38 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:39.469310329Z [5/24/2021] [11:30:39 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:39.497682660Z [5/24/2021] [11:30:39 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:39.501601616Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:39.501711263Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:39.513985608Z [5/24/2021] [11:30:39 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:40.528184101Z [5/24/2021] [11:30:40 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:40.560836662Z [5/24/2021] [11:30:40 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:40.564276365Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:40.564379660Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:40.575981216Z [5/24/2021] [11:30:40 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:41.592949958Z [5/24/2021] [11:30:41 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:41.627396315Z [5/24/2021] [11:30:41 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:41.632268686Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:41.632394592Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:41.643818576Z [5/24/2021] [11:30:41 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:42.651640608Z [5/24/2021] [11:30:42 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:42.670562656Z [5/24/2021] [11:30:42 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:42.672413006Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:42.672475875Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:42.682931222Z [5/24/2021] [11:30:42 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:43.699601824Z [5/24/2021] [11:30:43 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:43.733502576Z [5/24/2021] [11:30:43 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:43.738095025Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:43.738216894Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:43.750483331Z [5/24/2021] [11:30:43 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:44.758365663Z [5/24/2021] [11:30:44 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:44.776419406Z [5/24/2021] [11:30:44 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:44.778631734Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:44.778694974Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:44.786186705Z [5/24/2021] [11:30:44 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:45.800429728Z [5/24/2021] [11:30:45 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:45.829984713Z [5/24/2021] [11:30:45 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:45.834014465Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:45.834132889Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:45.843794245Z [5/24/2021] [11:30:45 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:46.857915179Z [5/24/2021] [11:30:46 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:46.889903619Z [5/24/2021] [11:30:46 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:46.893274840Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:46.893372173Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:46.904633677Z [5/24/2021] [11:30:46 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:47.912830827Z [5/24/2021] [11:30:47 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:47.929573400Z [5/24/2021] [11:30:47 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:47.932831790Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:47.932880919Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:48.082947468Z [5/24/2021] [11:30:48 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:49.097156222Z [5/24/2021] [11:30:49 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:49.130648997Z [5/24/2021] [11:30:49 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:49.134507305Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:49.134885801Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:49.147410032Z [5/24/2021] [11:30:49 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:50.160650484Z [5/24/2021] [11:30:50 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:50.189894195Z [5/24/2021] [11:30:50 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:50.193946113Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:50.194065222Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:50.204199480Z [5/24/2021] [11:30:50 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:51.217936595Z [5/24/2021] [11:30:51 PM] [Migrate  ] › ℹ  info      Current database version: none,
2021-05-24T23:30:51.243853825Z [5/24/2021] [11:30:51 PM] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...,
2021-05-24T23:30:51.247546154Z migration file "20180618015850_initial.js" failed,
2021-05-24T23:30:51.247641449Z migration failed with error: create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
2021-05-24T23:30:51.264079211Z [5/24/2021] [11:30:51 PM] [Global   ] › ✖  error     create table `auth` (`id` int unsigned not null auto_increment primary key, `created_on` datetime not null, `modified_on` datetime not null, `user_id` int unsigned not null, `type` varchar(30) not null, `secret` varchar(255) not null, `meta` json not null, `is_deleted` int unsigned not null default '0') - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json not null, `is_deleted` int unsigned not null default '0')' at line 1,
```
</details>

**Comment by chaptergy** [comment] 2021-05-25 08:00
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/896

**Closed by chaptergy** 2021-05-25 08:00 UTC
Labels: product-support
