### ISSUE TITLE
issue!!!

### ISSUE THREAD

**Issue by AiPacino** [jc21/nginx-proxy-manager#1626] opened 2021-12-03 00:52 UTC
```
[12/3/2021] [12:48:57 AM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[12/3/2021] [12:48:57 AM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[12/3/2021] [12:48:57 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[12/3/2021] [12:48:57 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[12/3/2021] [12:48:57 AM] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
[12/3/2021] [12:48:57 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/3/2021] [12:48:57 AM] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
[12/3/2021] [12:48:57 AM] [Global   ] › ℹ  info      Backend PID 236 listening on port 3000 ...
[12/3/2021] [12:49:00 AM] [SSL      ] › ✖  error     Error: Command failed: /usr/sbin/nginx -t -g "error_log off;" 
nginx: [emerg] invalid number of arguments in "set_real_ip_from" directive in /etc/nginx/conf.d/include/ip_ranges.conf:292
nginx: configuration file /etc/nginx/nginx.conf test failed
    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
   at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

![image](https://user-images.githubusercontent.com/8651400/144526170-6d074d19-5c5b-4efa-ab10-cef992555d42.png)

![image](https://user-images.githubusercontent.com/8651400/144526241-c2b8f390-2c63-498b-879a-ea2b19e3f0dd.png)

**Comment by chaptergy** [comment] 2021-12-03 15:08
First of all, please use a title that actually describe the issue, not just `issue!!!`. Second of all, this is a duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1405.

**Closed by chaptergy** 2021-12-03 15:08 UTC
Labels: bug
