### ISSUE TITLE
NPM login deny with access list

### ISSUE THREAD

**Issue by techc0de** [jc21/nginx-proxy-manager#843] opened 2021-01-25 20:17 UTC
**Describe the bug**
- Access List not working with NPM page itself
- 
- What version of Nginx Proxy Manager is reported on the login page?
- 2.7.3 (Docker)

**To Reproduce**
1. Access List >> Add Access List
2. add a username: user1
3. check 'Satisfy Any'
4. Authorization>> enter a username, and password
5. Access >> Allow > enter a public IP address
6.  click Save
7.  go to Proxy Hosts > edit the NPM subdomains> Access List > select the list name
8.  click Save
9.  go to NPM URL: https://npm.mydomain.com

**Expected behavior**
1. Go to the NPM url: npm.mydomain.com
2. Authentication window popup: username,  password
3. enter credentials, enter email address and password.
4. Log into the NPM dashboard

**Screenshots**

**Operating System**
- Ubuntu 20, Docker 

**Additional context**
After I enter the credentials in the auth pop up box, it denied.
It goes into a loop after I enter the credentials even it's correct.
If I click cancel, the domain would direct to: https://npm.mydomain.com/login.
It then let me enter my email, and password, but it wouldn't let me log in.
I've tried the 'Access'  in the Access List with IP and no ip, but error persist.
I've also tried turn off proxy option in Cloudflare as well.
However, the access list works with other services.

NPM current setup: 
- Cloudflare
- Google VM
- web admin port: 81
- http: 80:80
- https: 443:443

**Comment by techc0de** [comment] 2021-05-08 20:15
I'm using NPM v2.9.1 as of today's date, the issue still persist.
I also added `real_ip_header CF-Connecting-IP;` in the  Custom Nginx Configuration box.

**Comment by chaptergy** [comment] 2021-05-12 22:47
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/334

**Closed by chaptergy** 2021-05-12 22:47 UTC
Labels: bug

**Comment by Raito00** [comment] 2021-06-03 11:02
I have the same problem with npm Auth Loop . Version 2.9.3

**Comment by techc0de** [comment] 2021-08-05 13:23
Hi,
I'm currently using v2.9.6, and the issue still persist.
The proxy access list works for other subdomains except NPM itself.
I don't understand why.

However, if I use the below proxy codes, the access list box will not prompt and let me log in.

`location / {
    include conf.d/include/force-ssl.conf;
    proxy_pass http://172.17.0.1:81;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
}`

**Comment by chaptergy** [comment] 2021-08-05 13:29
This issue was closed as a duplicate. Please only use the open issue to add helpful information, since it will get lost here.
