### ISSUE TITLE
Add Upstream to Proxy Hosts

### ISSUE THREAD

**Issue by mmhy2003** [jc21/nginx-proxy-manager#410] opened 2020-05-14 13:49 UTC
I love your solution but I wish if you can extend your solution feature to support upstream where you can add multiple IP/Hosts per proxy host **Loadbalancing**

**Comment by netsujit** [comment] 2020-05-19 06:57
+1 for this ^^

**Comment by jc21** [comment] 2020-05-20 11:44
There are some considerations with upstreams but yep definitely on the nice-to-have list!

**Comment by SDekkers** [comment] 2020-09-02 08:30
Could we maybe bump this to the should-have list? 
There isn't any other way to configure upstreams having multiple hosts it seems.

**Comment by chaptergy** [comment] 2021-05-11 20:51
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/156

**Closed by chaptergy** 2021-05-11 20:51 UTC
Labels: enhancement
