### ISSUE TITLE
Improve Streams description or destination

### ISSUE THREAD

**Issue by Na0mir** [jc21/nginx-proxy-manager#501] opened 2020-07-12 08:01 UTC
Is that possible to add a title/description to the Streams proxy ?

Or even better, be able to put an hostname in the destination (for now limited to IP) 
Thanks!

**Comment by chaptergy** [comment] 2021-05-12 14:51
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/44

**Closed by chaptergy** 2021-05-12 14:51 UTC
Labels: enhancement
