### ISSUE TITLE
Example/Standard configs

### ISSUE THREAD

**Issue by palitu** [jc21/nginx-proxy-manager#303] opened 2020-02-22 13:27 UTC
**Is your feature request related to a problem? Please describe.**
There are a number of standard proxy configs which are required for many self hosted solutions (ie Jellyfin, sonarr, gitea, grafana, etc)

**Describe the solution you'd like**

It would be great to be able to select from a drop down list and it will pre-fill a standard reverse proxy for that application.  I am struggling with jellyfin right now, and i am sure that many people have already solved this problem using your (fantastic) UI.

**Describe alternatives you've considered**
roll back to letsencrypt docker container :(

**Additional context**
the lets encrypt contianer (linuxserver.io i think) has a large list of sample conf's that it ships with.

thanks!

**Comment by jc21** [comment] 2020-02-23 23:06
This is a duplicate of #71

**Closed by jc21** 2020-02-23 23:06 UTC
Labels: enhancement
