### ISSUE TITLE
SSL-Certificates, Pages shows wrong expire dates

### ISSUE THREAD

**Issue by touro411** [jc21/nginx-proxy-manager#953] opened 2021-03-16 16:20 UTC
Hello,

I noticed that the wrong expiry dates are displayed on the SSL certificate overview page. However, the certificates are renewed in the background, so only a display problem.

I'm using NPM 2.8 and mariadb 10.4.

Greetings
![Screenshot 2021-03-16 171506](https://user-images.githubusercontent.com/34543800/111343548-d2c29900-867b-11eb-8413-2d7a55f46481.jpg)

**Comment by HNGamingUK** [comment] 2021-05-21 21:34
I have noticed the same also, recently had one where it was red and showing a past date. Checked the cert on the URL and it infact was fine. Opened the cert menu and clicked renew and the date updated to the cert attached to the URL. 

Seems to be that certbot is renewing the certificate in the background but not reflecting in the UI (even after a container restart) 

I am on version 2.9.3

**Comment by chaptergy** [comment] 2021-05-22 07:23
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/792

**Closed by chaptergy** 2021-05-22 07:23 UTC
Labels: bug
