### ISSUE TITLE
Show logs in ui

### ISSUE THREAD

**Issue by inmanturbo** [jc21/nginx-proxy-manager#724] opened 2020-11-17 14:29 UTC
**Is your feature request related to a problem? Please describe.**
Not really Just a bell or a whistle, so to speak

**Describe the solution you'd like**
show access logs in ui, either with link in the context menu for where you select to edit the host, or show all under `Audit Log`. Maybe even better show error log under `Audit Log` and access logs under context menu for each host.

Just a thought. I think it would be a great addition and it wouldn't break anything.

**Comment by Salvora** [comment] 2020-11-23 21:57
second this

**Comment by Peutchwice** [comment] 2020-11-24 10:48
third this :)

**Comment by Rustymage** [comment] 2021-01-12 07:24
I log all traffic to a central rsyslog server using the following text in the `Advanced` section of each proxy host:

`access_log syslog:server=192.168.1.115:519,tag=extensions,severity=info combined;
error_log syslog:server=192.168.1.115:519,tag=extensions,severity=debug;`

**Comment by inmanturbo** [comment] 2021-01-12 15:44
> I log all traffic to a central rsyslog server using the following text in the `Advanced` section of each proxy host:
> 
> `access_log syslog:server= <RSYSLOG_IP:PORT>,tag= <PROXY_NAME>,severity=info combined; error_log syslog:server=<RSYSLOG_IP:PORT>,tag= <PROXY_NAME>,severity=debug;`

That's a great idea. Thanks for mentioning it!

**Comment by chaptergy** [comment] 2021-05-12 20:59
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/401

**Closed by chaptergy** 2021-05-12 20:59 UTC
Labels: enhancement
