### ISSUE TITLE
Add ngx_http_geoip2_module

### ISSUE THREAD

**Issue by darkcloud784** [jc21/nginx-proxy-manager#595] opened 2020-09-04 16:39 UTC
Adding ngx_http_geoip2_module module (https://github.com/leev/ngx_http_geoip2_module) would be useful for visualizing locations using docker images such as https://github.com/gilbN/geoip2influx

**Comment by zorflieg** [comment] 2020-11-03 01:02
I agree integrating geo location for geoblocking is a big part of protecting an NGINX install.  I tried shoe horning it in through apk edge install and such but it resulted in bad nginx 'stream' config errors.  It would be great to have the GeoIP2 module.

**Comment by PsychoD** [comment] 2021-01-15 17:10
+1

**Comment by ansred** [comment] 2021-03-13 09:46
That would be a great thing to have geoip maxmind is part of the Access List, options of restrictions + adding exceptions of IPs if needed

**Comment by chaptergy** [comment] 2021-05-12 17:53
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/46

**Closed by chaptergy** 2021-05-12 17:53 UTC
Labels: enhancement
