### ISSUE TITLE
Log Analyzer

### ISSUE THREAD

**Issue by wasn-eu** [jc21/nginx-proxy-manager#698] opened 2020-11-06 22:09 UTC
**Describe the solution you'd like**
would like to see a log analyzer in the gui.
a short overview of actual access and historic

**Comment by ansred** [comment] 2020-11-12 03:30
Or maybe to send a syslog traffic to Splunk or any syslog server. Yeah that would be nice.

**Comment by chaptergy** [comment] 2021-05-12 20:24
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/401

**Closed by chaptergy** 2021-05-12 20:24 UTC
Labels: enhancement
