### ISSUE TITLE
"exec format error" on arm64/armv7 (Raspberry Pi 3B+)

### ISSUE THREAD

**Issue by fr9ncis** [jc21/nginx-proxy-manager#446] opened 2020-06-03 19:27 UTC
I keep getting 
`` db_1   | standard_init_linux.go:211: exec user process caused "exec format error" ``
followed by 
`` app_1  | [6/3/2020] [7:21:29 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db ``
(obviously, since db just crashed) which then leads to Bad Gateway errors when trying to login into the WebUI.

**Target architecture**: armv7l, armv7 as well as aarch64/arm64.
**Tested on**: Raspbian Lite, Ubuntu 20.04 Server 64bit and HypriotOS/armv7 (all of them were clean installs)

This is my first time running Nginx Proxy Manager on my RPI3 but I've been using on my x86_64 server just fine.

I'm not quite sure wether docker or s6 isn't detecting my archtitecture properly and thus pulling the wrong images. I seem, however, unable to specify the target arch myself (i.e. 
```yml
 image: 'jc21/nginx-proxy-manager:latest-armv7'
```
would be helpful (but again - I can't seem to do that..)

I suppose this is a bug since the guide indicates that no special setup needs to be done for ARM devices 

> 'The docker images are a manifest of all the architecture docker builds supported, so this means you don't have to worry about doing anything special and you can follow the common instructions above.'
Source: [Nginx Proxy Manager Setup Page](https://nginxproxymanager.com/setup/)

Edit: Spelling.

**Comment by fr9ncis** [comment] 2020-06-04 12:16
This isn't really a fix itself, but as a workaround for anyone else encountering this issue:

Replace
``image: jc21/mariadb-aria:10.4``
with
``image: yobasystems/alpine-mariadb:latest``
and it should work.

Please either update the guide or fix the jc21/mariadb-aria image.

**Comment by chaptergy** [comment] 2021-05-12 12:49
Closing as a duplicate of https://github.com/jc21/nginx-proxy-manager/issues/212

**Closed by chaptergy** 2021-05-12 12:49 UTC
Labels: bug
