### ISSUE TITLE
Why force transfer frontend Host to backend?

### ISSUE THREAD

**Issue by proy27** [jc21/nginx-proxy-manager#733] opened 2020-11-20 08:25 UTC
Why force transfer frontend Host to backend?
nginx-proxy-manager/docker/rootfs/etc/nginx/conf.d/include/proxy.conf

> add_header       X-Served-By $host;
> ### proxy_set_header Host $host;
> proxy_set_header X-Forwarded-Scheme $scheme;
> proxy_set_header X-Forwarded-Proto  $scheme;
> proxy_set_header X-Forwarded-For    $remote_addr;
> proxy_set_header X-Real-IP          $remote_addr;
> proxy_pass       $forward_scheme://$server:$port;

**Comment by chaptergy** [comment] 2021-05-12 21:12
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/127

**Closed by chaptergy** 2021-05-12 21:12 UTC
Labels: enhancement
