### ISSUE TITLE
Responsive design issue/UI layout issue.

### ISSUE THREAD

**Issue by allebb** [jc21/nginx-proxy-manager#123] opened 2019-04-20 00:03 UTC
Using a Windows 10 PC, reproducible in both Google Chrome and Firefox, with my screen resolution **2560 x 1440** I get the following experience:

![Capture2](https://user-images.githubusercontent.com/767628/56448516-c1de4100-6307-11e9-9eb8-8a5bb1592368.JPG)

If I get time this weekend I'll submit a PR to fix it :)

Thanks for a great tool @jc21

**Comment by kolbii** [comment] 2019-04-23 18:40
Then can you please also fix the following use case:

![image](https://user-images.githubusercontent.com/47610371/56607033-da9c6e80-6607-11e9-87cb-f99dc299bb8c.png)

![image](https://user-images.githubusercontent.com/47610371/56607065-f0aa2f00-6607-11e9-91a4-a8be5c666b4f.png)

**Comment by jc21** [comment] 2019-04-23 21:22
For the main issue, it feels like there would be some errors in the browser console that would help

**Comment by jonfairbanks** [comment] 2019-05-04 08:50
Also seeing this on a 4k display. There are no errors in the console, only the welcome messages. 

The following temporarily fixes it for me:

<img width="1431" alt="Screenshot_7" src="https://user-images.githubusercontent.com/1957806/57176575-59ff1e80-6e0e-11e9-92ef-e39e26144360.png">

Find the div with id=app. In Chrome, uncheck `display:flex`. Alternatively, locate `.page` in main.css and remove the same.

<img width="1435" alt="Screenshot_8" src="https://user-images.githubusercontent.com/1957806/57176603-b3674d80-6e0e-11e9-9883-b709b5619c55.png">

You should now see a fixed layout minus the footer. 

<img width="1430" alt="Screenshot_9" src="https://user-images.githubusercontent.com/1957806/57176612-cb3ed180-6e0e-11e9-80a3-7b1f273dadd5.png">

To fix the footer, search for the <footer> and add the highlighted CSS classes either in Chrome, or in main.css. 

Unfortunately any reboots to the host or Docker container will result in having to redo these steps.

**Comment by jc21** [comment] 2019-05-08 00:16
The UI is based entirely on Tabler, and it uses the layout and styles from there. It's likely that it's a problem with their project.

**Comment by jc21** [comment] 2019-05-08 01:33
Confirmed that this is because tabler released a new version compatible with latest bootstrap. Have rolled back tabler and will be fixed in 2.0.13

**Closed by jc21** 2019-05-08 01:33 UTC
Labels: bug

**Comment by jonfairbanks** [comment] 2019-05-08 03:48
Thanks a bunch!
