### ISSUE TITLE
Basic Auth not prompting for username and password.

### ISSUE THREAD

**Issue by colonelmattyman** [jc21/nginx-proxy-manager#590] opened 2020-08-30 13:04 UTC
I am unable to get Basic Auth to work .
In the access list I've:
- enabled "Satisfy any"
- added a username and password
- left the access tab as default

I've then attached this access list to the Proxy Host and saved it.
When I connect to the URL it doesn't prompt for username and password and just goes straight into the web page without authorising.

I've disabled and re-enabled the proxy host which hasn't helped and even restarted the container.

**Comment by aronwk-aaron** [comment] 2020-08-31 14:42
#148 may be your issue, you can it for a workaround

**Comment by colonelmattyman** [comment] 2020-08-31 16:26
Thanks for that. I'll take a look.

**Comment by chaptergy** [comment] 2021-05-10 21:55
Closing this as a duplicate of https://github.com/jc21/nginx-proxy-manager/issues/148

**Closed by chaptergy** 2021-05-10 21:55 UTC
Labels: product-support

**Comment by W1BTR** [comment] 2025-06-30 23:28
Adding
```
auth_basic            "Authorization required";
auth_basic_user_file  /data/access/{{ access_list_id }};
```
Causes it to fail and show that host as "offline" for me, unfortunately.
