### ISSUE TITLE
Mobile View Not Showing Top Menu

### ISSUE THREAD

**Issue by egooner** [jc21/nginx-proxy-manager#1413] opened 2021-09-21 08:20 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

The top menu showing Dashboard, Hosts, Access Lists, SSL Certificates etc is not visible from the mobile platform.
Using Google Chrome on Android (latest) or Firefox this menu is not visible.

**Nginx Proxy Manager Version**

v2.9.9

**To Reproduce**
1. Login to NPM on mobile device
2. Check out that the top menu is not visible

Manually entering the URL to get to access lists works but the link is not there

**Expected behavior**

Should show the menu and as close an experience on mobile to desktop

**Screenshots**

![NPMScreenshot_20210921-091323](https://user-images.githubusercontent.com/13605448/134136753-edf90016-25e9-4731-a352-e5096487008c.png)

**Operating System**

Using Raspberry Pi4 

**Additional context**

Deployed using Portainer v2.6.3

**Comment by chaptergy** [comment] 2021-09-21 09:04
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/702

**Closed by chaptergy** 2021-09-21 09:04 UTC
Labels: bug
