### ISSUE TITLE
Proxied URL not loading correct vhost from source server.

### ISSUE THREAD

**Issue by archness1** [jc21/nginx-proxy-manager#460] opened 2020-06-15 04:16 UTC
**What is troubling you?**

I have a Matomo site setup that I use to provide stats tracking across~10 other websites.  I use proxied domains pointed at the same Matomo instance hosted on a cPanel server.

My setup is: Matomo installed at internal url of: http://webstats.example1.com
Externally it is: https://stats.example1.com.  (This is proxied by NPM)
Then I have https://stats.example2.com, https://stats.example3.com

All of these are proxied to https://webstats.example1.com on the cPanel server.

When I load https://stats.example1.com, it loads a different vhost from the cPanel server.   It should load https://webstats.example1.com.  Instead it loads http://example6.com.

Is there an advanced config I need to add for nginx to proxy this correctly?

**Comment by theraw** [comment] 2020-06-18 14:21
https://github.com/jc21/nginx-proxy-manager/blob/master/docker/rootfs/etc/nginx/conf.d/include/proxy.conf#L2

to be able to reverse proxy `stats.example1.com` to `webstats.example1.com` you have to add 
proxy_set_header Host webstats.example1.com;

but NPM does not have a feature to set custom HOST so this looks a bit not possible for now 🤒

**Comment by chaptergy** [comment] 2021-05-12 13:43
If this is an enhancement it would be a duplicate of https://github.com/jc21/nginx-proxy-manager/issues/127

**Closed by chaptergy** 2021-05-12 13:43 UTC
Labels: product-support
