### ISSUE TITLE
LDAP authent 

### ISSUE THREAD

**Issue by Mr-icat59** [jc21/nginx-proxy-manager#638] opened 2020-10-07 14:34 UTC
**Describe the solution you'd like**

Hello, is it possible to add an LDAP authent ? 

I tried to add an apache proxy with ldap authent ( yes i know it's weird) in front of the nginx proxy manager, but I have an error like "unauthorized" when i tried to authenticate with my user in the proxy manager.

**Comment by chaptergy** [comment] 2021-05-12 19:05
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/159

**Closed by chaptergy** 2021-05-12 19:05 UTC
Labels: enhancement
