### ISSUE TITLE
SSL on npm admin page won‘t let me login (with access list)

### ISSUE THREAD

**Issue by AlfaJackal** [jc21/nginx-proxy-manager#610] opened 2020-09-21 18:39 UTC
I configured my nginx with a valid ssl cert to access the npm web interface (10.10.0.4:81). Cert is valid and I can see the login page when I open https://nginx.domain.com

But I am not able to login. I can enter my credentials but the admin page will not be shown. Instead I always see the blank login fields.
Logging in without access profile works perfectly with and without ssl.

What am I missing here?

**Comment by chaptergy** [comment] 2021-05-12 18:15
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/334

**Closed by chaptergy** 2021-05-12 18:15 UTC
