### ISSUE TITLE
Unable to access radarr/sonarr/prowlarr remotely 

### ISSUE THREAD

**Issue by rainman369** [jc21/nginx-proxy-manager#1557] opened 2021-11-04 03:13 UTC
I can access the arr apps via local ip, but my reverse dns access is no longer working (radarr.local.org, sonarr.local.org, etc). I just keep getting the attached screenshot. Any ideas?

![help](https://user-images.githubusercontent.com/61566782/140251987-670d04c6-6f0c-4c37-ae8e-e002fc9acc46.png)

**Comment by chaptergy** [comment] 2021-11-04 10:59
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1319

**Closed** 2021-11-04 11:00 UTC
Labels: bug
