### ISSUE TITLE
{add proxy, add 404, add redirection} no popup anymore

### ISSUE THREAD

**Issue by NA3** [jc21/nginx-proxy-manager#658] opened 2020-10-16 03:41 UTC
only add stream bouton open popup sine 2.6 version
here the error when click on "Host" add button
![Sans titre](https://user-images.githubusercontent.com/3059879/96210387-1e103880-0f72-11eb-9de1-1e68b02c69d3.png)

**Comment by jc21** [comment] 2020-10-16 03:47
Can't reproduce this with that release on 3 different deployments. Try another browser perhaps? Might be an aggressive caching issue?

**Comment by NA3** [comment] 2020-10-16 03:54
was working a few hours ago, i have prune my container, delete my image and make a new docker-compose and now only add stream work

**Comment by jc21** [comment] 2020-10-16 03:56
I'm about to release 2.6.1 soon so maybe this rebuild will make a difference for you

**Comment by NA3** [comment] 2020-10-16 03:59
i have close chrome, and clear chache and coockie, and it's good now
Sry.
Ps: do you think make it working with ingress for use it on k8s cluster?

**Comment by jc21** [comment] 2020-10-16 04:01
Can't really comment - I haven't tried and not really up to speed with kubernetes yet

**Comment by henkisdabro** [comment] 2020-10-20 13:42
I have a similar problem after pulling in the image for 2.6.1 and recreating container. Here's what's showing when clicking "Add Proxy Host":

<img width="647" alt="Nginx_Proxy_Manager" src="https://user-images.githubusercontent.com/477513/96594275-042d7780-131d-11eb-97d7-e680a6f6dda3.png">

**Comment by chaptergy** [comment] 2021-05-12 19:28
It's hard to debug remotely. As there hasn't been activity in a while now, I will close this issue.

**Closed by chaptergy** 2021-05-12 19:28 UTC
Labels: bug
