### ISSUE TITLE
Add Option to make Front End TLS

### ISSUE THREAD

**Issue by jamesonuk** [jc21/nginx-proxy-manager#974] opened 2021-03-25 14:29 UTC
I would like to see the Front End be accessible over HTTPS rather than plain HTTP.
It would be great if you could add a certificate via the front end and assign this as the one to use for the NPM front end.
I guess you would also need to allow configuration of what port it runs on.

I did have a look at the code to see if I could do this myself but my experience of node is restricted to hello world examples (I can configure Java managed servers through :))   If someone could point me towards where in the code the actual server is instantiated I might even be able to submit a pull request...

**Comment by chaptergy** [comment] 2021-05-12 23:25
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/182

**Closed by chaptergy** 2021-05-12 23:25 UTC
Labels: enhancement
