### ISSUE TITLE
linux/arm64/v8

### ISSUE THREAD

**Issue by dash82** [jc21/nginx-proxy-manager#602] opened 2020-09-10 14:41 UTC
**Is your feature request related to a problem? Please describe.**
Error in the docker logs for mariadb. Looks to be a difference between arm64/v7 & v8.
standard_init_linux.go:211: exec user process caused "exec format error"

**Describe the solution you'd like**
include the v8 manifest for pi 4 please :) 

**Describe alternatives you've considered**
Use your solution on my x86 box and it works like a charm. Just want to move some services on the pi 4 for some separation.

**Additional context**
Problem seems to be mostly with the mariadb portion. Looks like the nginx portion is just complaining that it cant connect to the db.. But might be good to have  v8 for all the services? I am running the pi on ubuntu server 20.04 if that makes any difference. First time issue logger, so please let me know if you need any further information.

**Comment by chaptergy** [comment] 2021-05-12 18:03
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/269

**Closed by chaptergy** 2021-05-12 18:03 UTC
Labels: enhancement
