### ISSUE TITLE
Domain Name Entry Field Size Limitation 

### ISSUE THREAD

**Issue by PaPaTheGMan** [jc21/nginx-proxy-manager#647] opened 2020-10-10 19:13 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
 **YES**
- Are you sure you're not using someone else's docker image?
 **YES**
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
 **N/A**

**Describe the bug**
- A clear and concise description of what the bug is.
 **Whenever I try to add and enter a domain name that's longer than 40 characters, the system hangs and I need to close the window.**
- What version of Nginx Proxy Manager is reported on the login page?
 **2.5.0**

**To Reproduce**
 **Proxy Hosts**
 **Add Proxy Host**
 **Type a Domain Name that's longer than 40 characters,  On the 41st character, the system will hang.**
 **Systems hangs, need to close the web page and start over.**

**Expected behavior**
 **I would expect the system to complete the Domain Entry as it does with shorter names.**

**Screenshots**

**Operating System**
- Please specify if using a Rpi, Mac, orchestration tool or any other setups that might affect the reproduction of this error.
 **The system is Intel Atom x5-Z8350 (4) @ 1.920GHz, with 2GB of memory (56% used) and a 16GB eMMC module (63% used).**

**Additional context**
Add any other context about the problem here, docker version, browser version if applicable to the problem. Too much info is better than too little.
 **The system is running Ubuntu 18.04.5 LTS x86_64 and docker-ce 5:19.03.13~3-0~ubuntu-bionic. NPM is typically accessed through Vivaldi (3.3.2022.47 (Stable channel) (64-bit)) from a Windows 10 Client.  It is headless, there is no direct display.**

**Comment by chaptergy** [comment] 2021-05-12 19:14
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/479

**Comment by chaptergy** [comment] 2021-05-12 19:14
If this is still an issue, please comment over there and we can reopen that issue.

**Closed by chaptergy** 2021-05-12 19:14 UTC
Labels: bug

**Comment by PaPaTheGMan** [comment] 2021-05-12 23:34
Yes, it's still an issue.

**Comment by chaptergy** [comment] 2021-05-12 23:50
Allright, but i'm reooening the other issue AS it contains Mord precisr information.

**Comment by PaPaTheGMan** [comment] 2021-05-12 23:52
Ok, thanks
