### ISSUE TITLE
Safari unable to open pages (NSPOSIXErrorDomain:100)

### ISSUE THREAD

**Issue by miit0o** [jc21/nginx-proxy-manager#617] opened 2020-09-28 13:56 UTC
**Describe the bug**
Safari on macOS and every browser on iOS is unable to open pages that are behind the reverse proxy. The error shown by the browser is "NXPOSIXErrorDomain:100" and only appears on desktop Safari. iOS does not report anything what so ever. Windows and Android work completely fine (Chrome, Edge and Firefox tested). I already found something, that has to do with that error, but should not affect this specific error. Our old Apache Proxy is working completely fine.

Note: Our Services linked to the proxy are using Apache, which usually should be no problem.
- Reported Version: 2.5.0

**To Reproduce**
- Use any macOS Device with Safari or iOS Device with any browser
- Visit https://cloud.neomind.eu
- See the error
- Try it with windows and any browser (where it works completely fine)

**Operating System**
- macOS (using Safari)
- iOS (using any Browser)

EDIT: Reproducing added

**Comment by florianeichincode** [comment] 2020-11-05 20:27
Same issue with workarround https://github.com/jc21/nginx-proxy-manager/issues/661

**Comment by chaptergy** [comment] 2021-05-12 18:23
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/661

**Closed by chaptergy** 2021-05-12 18:23 UTC
Labels: bug
