### ISSUE TITLE
Add self generated certificate as SSL provider

### ISSUE THREAD

**Issue by Syam** [jc21/nginx-proxy-manager#605] opened 2020-09-10 17:31 UTC
I am trying to expose some HTTPS services to LAN only.
But when adding a proxy, Nginx Proxy Manager only offer `Letsencrypt ` or `None` as provider.

Is it possible to add a self generated certificate as SSL provider ?

Thank,

**Comment by chaptergy** [comment] 2020-10-03 20:10
When switching to the "SSL Certificates" tab and clicking on the "Add SSL Certificate" button in the upper right corner of the card (Not the big one in the center) you can choose to upload a custom certificate.  
This certificate can then be selected for the host.
![Screenshot from 2020-10-03 22-06-06](https://user-images.githubusercontent.com/26956711/95000880-02498180-05c5-11eb-93bc-c11ec0e7318c.png)

However it seems since version 2.5.0 the custom certificate upload is broken. See https://github.com/jc21/nginx-proxy-manager/issues/594

**Comment by BlackF09** [comment] 2020-10-04 01:14
@chaptergy: I'm unsure if the author meant a third option besides _LE_ an _Custom_ (before step three) like "Own CA". OpenSSL could generate a quick self signed certificate with the given name. I think with this scenario we could even leave out the whole renewal management, just let it generate a new cert eg. after year. Only give the CA certificate to download that it could be added to clients.

Besides that it's a little bit confusing if two buttons with the same name do different things ("Add SSL Certificate").

**Comment by jc21** [comment] 2020-11-22 06:32
It was a conscious decision to make the main path for SSL certificate generation use Let's Encrypt because that was the goal of this project. Custom SSL certificates were added by request later in the game.

That said I agree it would be pretty easy to integrate `mkcert` into the project to generate self-signed certs on the fly and then make it part of the Host creation as an option.

**Comment by chaptergy** [comment] 2021-05-12 18:08
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/593

**Closed by chaptergy** 2021-05-12 18:08 UTC
Labels: enhancement
