### ISSUE TITLE
Folder / Groups

### ISSUE THREAD

**Issue by JSmythSSG** [jc21/nginx-proxy-manager#855] opened 2021-02-02 13:21 UTC
As an enhancement would it be possible to create groups/folders in Proxy Hosts to allow for better organisation.

So all your proxies for one domain could grouped in one place.

**Comment by chaptergy** [comment] 2021-05-12 22:58
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/409

**Closed by chaptergy** 2021-05-12 22:58 UTC
