### ISSUE TITLE
Automatic DNS Record Addition

### ISSUE THREAD

**Issue by Stetsed** [jc21/nginx-proxy-manager#1351] opened 2021-08-26 19:48 UTC
**Is your feature request related to a problem? Please describe.**

I am frustrated when I am adding new stuff to my Nginx-proxy-manager and then I have to go to cloudflare and add the same record there. Sometimes I even forget as I have a local DNS redirect which redirects everything automaticaly to NPM. So I then sometimes forget which can be annoying when I want other people to be able to use it.

**Describe the solution you'd like**

It would be nice if NPM could integrate with for example the Cloudflare API(I use cloudflare) to automatically add DNS records, it does this aswell for the SSL certificates so it shouldn't actually be to hard.(Although I am not a coder in this type so idrk)

**Describe alternatives you've considered**

**Additional context**

**Comment by chaptergy** [comment] 2021-10-05 19:16
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1228.

**Closed by chaptergy** 2021-10-05 19:16 UTC
Labels: enhancement
