### ISSUE TITLE
Support multiple upstream server

### ISSUE THREAD

**Issue by allblue** [jc21/nginx-proxy-manager#620] opened 2020-09-30 04:46 UTC
**Is your feature request related to a problem? Please describe.**
I am using the PVE virtualization platform with a decentralized design, log in to any  node tcp 8006 port to manage the cluster.
However，currently npm can only reverse proxy a single node.

**Describe the solution you'd like**
In order to prevent the  node from going down, it is hoped to add  multiple upstream hosts supoort to realize the main-standby switch, eg “Forward Hostname / IP”  can be configured as a list with weight. 

**Describe alternatives you've considered**
Configure multiple reverse proxies in npm

**Additional context**
none

**Comment by elit3ge** [comment] 2020-11-24 10:05
Yes please! +1

**Comment by chaptergy** [comment] 2021-05-12 18:26
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/156

**Closed by chaptergy** 2021-05-12 18:26 UTC
Labels: enhancement
