### ISSUE TITLE
button to add custom certificate does not work

### ISSUE THREAD

**Issue by miguelwill** [jc21/nginx-proxy-manager#1700] opened 2021-12-29 13:12 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
when pressing the button to add a custom certificate, it does nothing, and when checking in the browser console, errors appear:

main.bundle.js?v=2.9.13:1 TypeError: Cannot read properties of undefined (reading 'value')
    at i.onRender (16.bundle.16.js?v=2.9.13:1)
    at i.O [as triggerMethod] (main.bundle.js?v=2.9.13:27)
    at i.render (main.bundle.js?v=2.9.13:27)
    at ae (main.bundle.js?v=2.9.13:27)
    at de.show (main.bundle.js?v=2.9.13:27)
    at i.showChildView (main.bundle.js?v=2.9.13:27)
    at i.showModalDialog (main.bundle.js?v=2.9.13:306)
    at main.bundle.js?v=2.9.13:27
    at main.bundle.js?v=2.9.13:27
r.oe @ main.bundle.js?v=2.9.13:1
Promise.catch (async)
showNginxCertificateForm @ main.bundle.js?v=2.9.13:27
click @ui.add @ 3.bundle.3.js?v=2.9.13:1
dispatch @ main.bundle.js?v=2.9.13:27
p.handle @ main.bundle.js?v=2.9.13:27
16.bundle.16.js?v=2.9.13:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at i.onRender (16.bundle.16.js?v=2.9.13:1)
    at i.O [as triggerMethod] (main.bundle.js?v=2.9.13:27)
    at i.render (main.bundle.js?v=2.9.13:27)
    at ae (main.bundle.js?v=2.9.13:27)
    at de.show (main.bundle.js?v=2.9.13:27)
    at i.showChildView (main.bundle.js?v=2.9.13:27)
    at i.showModalDialog (main.bundle.js?v=2.9.13:306)
    at main.bundle.js?v=2.9.13:27
    at main.bundle.js?v=2.9.13:27

**Nginx Proxy Manager Version**
v2.9.13

**To Reproduce**
1. Go to 'SSL Certificates'
2. Click on 'Add SSL Certificate '
3. Select 'Custom'

**Expected behavior**
the form for new custom certificate should appear

**Operating System**
service installed on docker/linux, and tests performed on chrome and edge

**Additional context**
version updated on 3 separate servers, and all have the same problem

**Comment by chaptergy** [comment] 2021-12-29 13:44
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1676

**Closed by chaptergy** 2021-12-29 13:44 UTC
Labels: bug
