### ISSUE TITLE
Export letsencrypt certificates

### ISSUE THREAD

**Issue by dgeordgy21** [jc21/nginx-proxy-manager#683] opened 2020-11-02 09:43 UTC
Hello,
Can you add a link to download each certificate generated by letsencrypt? It's usefull to put it in adguard for exemple DNS-over-TLS.
`privkey.pem`  : the private key for your certificate.
`fullchain.pem`: the certificate file used in most server software.

Thes files are located in letsencrypt/live/npm-XX/

Thank you in advance.

**Comment by samborambo** [comment] 2020-11-12 13:19
I would also like to be able to link to the cert folder based on the site name. Its useful for npm to handle renewal for certs for services other than web.

I can see where the numbered folders map to but having site name folders would ease configuration. Also concerned numbering may change, breaking cert paths.

**Comment by Salamafet** [comment] 2020-12-07 08:02
Same here.

I use NPM on my Synology. I need to import the generate certificate for use it with Drive Client (desktop app).
The Drive App is not using a web protocol.

**Comment by nayefalebrahim** [comment] 2020-12-13 16:00
First of all great project, really top-notch!

This feature would be helpful, as I'm using wildcard certs which I wish I could export from the UI.

**Comment by cromulus** [comment] 2021-03-17 21:47
If you have many sites and many ssl certs, it's difficult to discern which npm-[0-9]* folder contains the certificates you want. 

I iterate through the nom folders and run `openssl x509 -noout -subject -in cert.pem` but it's sub-optimal.

**Comment by chaptergy** [comment] 2021-05-12 20:05
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/404

**Closed by chaptergy** 2021-05-12 20:05 UTC
Labels: enhancement

**Comment by Qaezar** [comment] 2021-08-12 14:53
+1, would love this too ! ;)

Thank you ^^

**Comment by samborambo** [comment] 2021-08-12 22:43
I solved this with a python script to copy out the certs to named folders. Not very well tested.

import sqlite3
import os
import glob

npmdir='/data/stacks/proxy/data'
certsdir='/data/ssl_certs/archive'
reldir='../archive'
files=['cert','chain','fullchain','privkey']

if not os.geteuid()==0:
    sys.exit('This script must be run as root!')

con = sqlite3.connect(npmdir+'/database.sqlite')
cur = con.cursor()

for row in cur.execute('SELECT id,domain_names FROM certificate'):
        certiddir='npm-'+str(row[0])
        src=certsdir+'/'+certiddir
        domainlist = list(row[1].replace('*','_').strip('"[]').split(','))
        recent = str(len(glob.glob(certsdir+'/'+certiddir+'/cert*.pem')))
        for domain in domainlist:
                dst='/data/ssl_certs/live/'+domain
                os.mkdir(dst)
                for file in files:
                        srcfile=str(src+'/'+file+recent+'.pem')
                        dstfile=str(dst+'/'+file+'.pem')
                        print(srcfile, dstfile)
                        os.link(srcfile, dstfile)

**Comment by ghostersk** [comment] 2021-09-10 06:51
Can you advice, how i can register a certificate without gui to Nginx Proxy manager?
My DNS provider does not support DNS challenge for NPM, but there is a script what can get me the certificate.
If I could save it in the NPM folder somewhere and NPM web gui would recognize it it would be awesome.

**Comment by marrobHD** [comment] 2022-02-13 22:08
I would also like to see this. I need to copy the SSL certificates over to mailcows SSL folder.
A better cert folder naming would be useful for building a script that does what I need.

**Comment by captainabloc** [comment] 2022-02-26 10:31
Hi all,
here a small script for retrieving latest Fullchain and Privatekey from NPM.
Usefull for example for Adguardhome certificates renewal:

```
#!/bin/bash


# ----------------------------------
# Colors
# ----------------------------------
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

echo -e "${YELLOW}\n
1       abc.xyz
5       a.abc.xyz
6       b.abc.xyz
7       c.abc.xyz
8       d.abc.xyz
9       e.abc.xyz
10      f.abc.xyz
11      g.abc.xyz
12      h.abc.xyz
13      i.abc.xyz
14      j.abc.xyz
18      k.abc.xyz
19      l.abc.xyz
20      m.abc.xyz
22      n.abc.xyz
23      o.abc.xyz
30      p.abc.xyz
31      q.abc.xyz
32      r.abc.xyz
33      s.abc.xyz
34      t.abc.xyz
35      u.abc.xyz
36      v.abc.xyz
37      w.abc.xyz
38      x.abc.xyz
39      y.abc.xyz
49      z.abc.xyz\n\n${NOCOLOR}"

# Ask the user for thecert number
echo certificat number ?
read varname
echo -e "${BLUE} FULLCHAIN:\n\n"
cat "$(ls -rt /etc/letsencrypt/archive/npm-$varname/fullchain* | tail -n1)"
echo -e "${NOCOLOR}\n\n "
echo -e "\n ${GREEN} PRIVATE:\n\n"
cat "$(ls -rt /etc/letsencrypt/archive/npm-$varname/privkey* | tail -n1)"
echo -e "${NOCOLOR}\n\n "
```
certificates numbers found in `/data/database.sqlite`

hope this can be useful

**Comment by corincorvus** [comment] 2023-05-20 21:57
> @Balya Thanks for your suggestion!
> 
> I run Prosody as a chat server (not on the NGINX Proxy Manager machine) and also need to transfer the certs to Prosody. I found the numbering scheme you use above not reliable, especially when making NPM configuration changes. So I opted for actually reading the relevant parts of NPM’s `.conf` files. (Excuse my bad Python…)
> 
> ```python
> #!/usr/bin/python3
> import re
> import os
> from pathlib import Path
> from paramiko import SSHClient
> from scp import SCPClient
> from paramiko import AutoAddPolicy, RSAKey, SSHClient
> 
> proxy_hosts_dir = '/home/admin/npm/data/nginx/proxy_host'
> archive_dir = '/home/admin/npm/letsencrypt/live'
> target_host = 'chat.mydomain.net'
> host_file = ''
> 
> for filename in os.listdir(proxy_hosts_dir):
>     file = os.path.join(proxy_hosts_dir, filename)
>     if os.path.isfile(file) and filename.endswith('.conf'):
>         with open(file) as f:
>             content = f.read();
>             m = re.search(r'server_name\s+(.*);', content)
>             if m:
>               s = m.group(1).split()
>               basename = ('_').join(s).replace("*", "x")
>               if target_host in s:
>                 f = re.search(r'ssl_certificate\s+/etc/letsencrypt/live(.*);', content)
>                 if f:
>                   fullchain = archive_dir + f.group(1)
>                 p = re.search(r'ssl_certificate_key\s+/etc/letsencrypt/live(.*);', content)
>                 if p:
>                   privkey = archive_dir + p.group(1)
> 
> client = SSHClient()
> client.load_system_host_keys()
> client.set_missing_host_key_policy(AutoAddPolicy())
> client.connect('prosody', username='myusername')
> sftp = client.open_sftp()
> sftp.put(fullchain, '/home/myusername/certs/' + target_host + '.fullchain.pem')
> sftp.put(privkey, '/home/myusername/certs/' + target_host + '.privkey.pem')
> sftp.close()
> ```
> 
> This script I run via root’s crontab on the NPM machine every night at 3:00 a.m. like so:
> 
> ```
> 0 3 * * * /home/admin/bin/ssl-chat.py
> ```
> 
> And on the Prosody machine, since it can’t reload correctly, at 3:10 a.m., also via root’s crontab:
> 
> ```
> 10 3 * * * prosodyctl --root cert import chat.mydomain.net /home/myusername/certs/
> ```
> 
> Works well so far. Maybe this can help others, too.

If i use your script and edit the paths and username etc. i get this Error:
Traceback (most recent call last):
  File "/root/./turn-ssl.sh", line 36, in <module>
    sftp.put(fullchain, '/opt/coturn/cert/' + target_host + '.fullchain.pem')
NameError: name 'fullchain' is not defined


No idea, how i can solve it

**Comment by LazyGatto** [comment] 2023-08-16 11:11
I tried to write a sample script to export certificates from Nginx Proxy Manager for use with mailcow mail server. You can adapt it to use with any application. https://github.com/LazyGatto/npm-cert-export

**Comment by psychogun** [comment] 2023-08-20 00:26
This is my take on it; one VM with NPM container (192.168.0.44)- another VM with a ZNC bouncer from where the bash script is run in a cron job from the root user, every 90 days. First execution is on the 25th of September 2023.

If you go to SSL Certificates in NPM, you can see which #number the certificate it is listed as (`/home/yoyo/podman/npm/letsencrypt/live/npm-13`) when you download it manually.

Cron:
`crontab -e
0 0 25 9 */90 /root/fullchain_download.sh`

I am running the ZNC bouncer as a regular user (`wwhite`) as a systems service (`systemctl --user start container-znc.service`) and I had some issues writing the files in to the shared directory with podman from that user. Therefore I opted to copy the `root` user's public key in to `.ssh/authorized_keys` on the `yoyo` user running NPM on the other machine.

```
#!/bin/bash


# Server details
SERVER_IP="192.168.0.44"
SSH_USER="yoyo"
REMOTE_DIR="/home/yoyo/podman/npm/letsencrypt/live/npm-13"

# Local directory
LOCAL_TMP="/home/wwhite/tmp"
LOCAL_ZNC="/home/wwhite/podman/znc"

# List of file names to download
FULLCHAIN="fullchain.pem"
PRIVKEY="privkey.pem"
FILES=("$FULLCHAIN" "$PRIVKEY")

echo "Attempting to connect to $SERVER_IP"

for FILE in "${FILES[@]}"; do
    scp "$SSH_USER@$SERVER_IP:$REMOTE_DIR/$FILE" "$LOCAL_TMP/"
    echo "$FILE downloaded to $LOCAL_TMP"
done

echo "Combining keys"
cat "$LOCAL_TMP/$PRIVKEY" > "$LOCAL_TMP/znc.pem"
cat "$LOCAL_TMP/$FULLCHAIN" >> "$LOCAL_TMP/znc.pem"

echo "Privkey and fullchain is combined to znc.pem"

mv "$LOCAL_TMP/znc.pem" "$LOCAL_ZNC"

echo "The combined znc.pem is moved in to the appropriate directory"

# Clean up process

rm $LOCAL_TMP/$FULLCHAIN
echo "Removed the temporary $FULLCHAIN"


rm $LOCAL_TMP/$PRIVKEY
echo "Removed the temporary $PRIVKEY"

chmod 0600 $LOCAL_ZNC/znc.pem
echo "Permission 0600 znc.pem"

```
