### ISSUE TITLE
SSO via Keycloak integration

### ISSUE THREAD

**Issue by southwestflavorz** [jc21/nginx-proxy-manager#476] opened 2020-06-24 03:23 UTC
**Is your feature request related to a problem? Please describe.**

The feature request is not related to a problem, but while nginx provides basic authentication, applications like keycloak provide greater flexibility for authentication.  

**Describe the solution you'd like**

Integration to Keycloak, or any SSO provider that would allow for authentication via google, github, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by jean-luc1203** [comment] 2020-07-12 16:48
2FA like [Authelia](https://github.com/authelia/authelia) portal who is allready Docker-ized. 
QR-code & OTP allready embeded.
It would be nice to tie them together

**Comment by joe307bad** [comment] 2020-12-06 19:43
[Keycloak works with `nginx-proxy-manager`!](https://github.com/jc21/nginx-proxy-manager/pull/753#issuecomment-739552690)

**Comment by chaptergy** [comment] 2021-05-12 14:08
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/437

**Closed by chaptergy** 2021-05-12 14:08 UTC
Labels: enhancement
