### ISSUE TITLE
Allow more than 5 users for authorization

### ISSUE THREAD

**Issue by internetfreak** [jc21/nginx-proxy-manager#736] opened 2020-11-21 01:50 UTC
Currently the UI only allows to add at most 5 users to allow authorization via ACL. It would be nice if we can add more than 5 users if necessary

**Comment by badincite** [comment] 2020-12-14 22:26
Also having the session limit option per user would be cool

**Comment by chaptergy** [comment] 2021-05-12 21:13
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/432

**Closed by chaptergy** 2021-05-12 21:13 UTC
Labels: enhancement
