### ISSUE TITLE
Please add the ability to enable ssl for nginx proxy manager port 81

### ISSUE THREAD

**Issue by marrobHD** [jc21/nginx-proxy-manager#325] opened 2020-03-13 13:37 UTC
**Is your feature request related to a problem? Please describe.**
All is fine. But I cant get ssl for the nginx proxy manager webinterface working-

**Describe the solution you'd like**
I want that a option will be added to enable ssl for npm webinterface

**Describe alternatives you've considered**
I dont know

**Additional context**

**Comment by ShadowPeo** [comment] 2020-03-18 19:55
+1 on this, however, to do it with a LetsEncrypt cert you would have to publish it with an external DNS entry which is less than ideal. Combining this with #137 and #313 would be ideal but beggers cannot be choosers

**Comment by miguelwill** [comment] 2020-03-18 20:38
in my case, I created a proxy_host that derives the connection to port 81, and this way I can use one or several names to get to the dashboard, use ssl custom or de let's encrypt, etc

**Comment by lopugit** [comment] 2020-03-25 05:00
It is a bit weird because it means anyone could sniff your passwords or even login automatically.

I'm just installing now but I'm gonna try add a reverse proxy to npm itself.

ps I just realised that npm stands for nginx proxy manager lol

**Comment by miguelwill** [comment] 2020-03-25 08:32
hehe, it also happened to me that a few days after using it I realized the meaning of NPM lol.  

over the proxy to port 81, I use it that way, and it left 81 only with internal access, and remote access I can achieve using a hostname dedicated to panel access, and with a valid let's encrypt certificate

**Comment by lopugit** [comment] 2020-03-25 09:40
Ahhh right if you use npm to make the SSL cert then you need a domain I
see. Come on @jc21 we need ip address SSL ;)

**Comment by Salvora** [comment] 2020-10-27 04:20
+1 for this.

**Comment by chaptergy** [comment] 2021-05-11 19:50
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/182

**Closed by chaptergy** 2021-05-11 19:50 UTC
Labels: enhancement
