### ISSUE TITLE
Impossible to add Custom SSL Certificate

### ISSUE THREAD

**Issue by Saxintosh** [jc21/nginx-proxy-manager#1693] opened 2021-12-28 21:59 UTC
Hello,
At least in version 2.9.13, it is not possible to add a custom certificate.

1. go to menu "SSL Certificate"
2. click button "Add SSL Certificate"
3. choose sub menu item "Custom"

Nothing happens and you can see a js error in the console:

[Error] TypeError: undefined is not an object (evaluating 'this.ui.domain_names[0].value') — 16.bundle.16.js:1:7199
	(anonymous function) (main.bundle.js:1:1936)
	promiseReactionJob
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.ui.domain_names[0].value')
	(anonymous function) (main.bundle.js:1:1941)
	promiseReactionJob

Whether using Safari or Chrome!

**Comment by jwebbstevens** [comment] 2021-12-29 04:31
@Saxintosh try https://github.com/jc21/nginx-proxy-manager/pull/1677 `pr-1667` ran into the same problem and this PR worked for me. Was able to add in Chrome Version 96.0.4664.110, haven't tested adding in Safari but only need to load one custom cert in my use case.

**Comment by chaptergy** [comment] 2021-12-29 08:24
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1676

**Closed by chaptergy** 2021-12-29 08:24 UTC
Labels: bug
