### ISSUE TITLE
Unable to run on aarch64

### ISSUE THREAD

**Issue by rahulmkhj** [jc21/nginx-proxy-manager#1134] opened 2021-05-29 10:53 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

"Bad Gateway" - on attempt to login.

**Nginx Proxy Manager Version:**

- v2.9.3

**To Reproduce**
1. created a docker-compose.yml with following content from [quick setup guide](https://nginxproxymanager.com/guide/#quick-setup):
```yaml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```
2. docker-compose up  ( I'm using [linuxserver/docker-compose](https://hub.docker.com/r/linuxserver/docker-compose) )

**Operating System:**

- Oracle Linux Server release 7.9

**Platform:**
- Oracle Cloud

**CPU Info:**
```
[opc@instance-20210529-1419 nginx-proxy-manager]$ sudo lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Model:                 1
BogoMIPS:              50.00
NUMA node0 CPU(s):     0-3
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```

Logs on DB container:
```
[i] pre-init.d - processing /scripts/pre-init.d/01_secret-init.sh
[i] mysqld not found, creating....
[i] MySQL directory already present, skipping creation
2021-05-29  9:51:05 0 [Note] /usr/bin/mysqld (mysqld 10.4.15-MariaDB) starting as process 1 ...
2021-05-29  9:51:05 0 [Note] Plugin 'InnoDB' is disabled.
2021-05-29  9:51:05 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-05-29  9:51:05 0 [Note] Server socket created on IP: '::'.
2021-05-29  9:51:05 0 [Warning] 'user' entry '@fb5deba43988' ignored in --skip-name-resolve mode.
2021-05-29  9:51:05 0 [Warning] 'proxies_priv' entry '@% root@fb5deba43988' ignored in --skip-name-resolve mode.
2021-05-29  9:51:05 0 [Note] Reading of all Master_info entries succeeded
2021-05-29  9:51:05 0 [Note] Added new Master_info '' to hash table
2021-05-29  9:51:05 0 [Note] /usr/bin/mysqld: ready for connections.
Version: '10.4.15-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
2021-05-29  9:51:09 3 [Warning] Aborted connection 3 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:12 4 [Warning] Aborted connection 4 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:15 5 [Warning] Aborted connection 5 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:18 6 [Warning] Aborted connection 6 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:21 7 [Warning] Aborted connection 7 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:24 8 [Warning] Aborted connection 8 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:30 9 [Warning] Aborted connection 9 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:33 10 [Warning] Aborted connection 10 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:36 11 [Warning] Aborted connection 11 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
2021-05-29  9:51:39 12 [Warning] Aborted connection 12 to db: 'npm' user: 'npm' host: '172.20.0.3' (Got an error reading communication packets)
```

Logs on App container:
```
[5/29/2021] [9:51:06 AM] [Global   ] › ℹ  info      Generating MySQL db configuration from environment variables
[5/29/2021] [9:51:06 AM] [Global   ] › ℹ  info      Wrote db configuration to config file: ./config/production.json
./run: line 18:   223 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   272 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   295 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[5/29/2021] [9:51:16 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   317 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   330 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   352 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[5/29/2021] [9:51:26 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   365 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   387 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   409 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
./run: line 18:   422 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[5/29/2021] [9:51:40 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   445 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
[5/29/2021] [9:51:43 AM] [Migrate  ] › ℹ  info      Current database version: none
./run: line 18:   458 Segmentation fault      (core dumped) node --abort_on_uncaught_exception --max_old_space_size=250 index.js
```

**While in the logs it says:  "Wrote db configuration to config file: ./config/production.json", I don't see a ./config directory being created.**

**Comment by chaptergy** [comment] 2021-05-29 17:06
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1128, please contribute any additional findings you have over there

**Closed by chaptergy** 2021-05-29 17:06 UTC
Labels: bug
