### ISSUE TITLE
Letsencrypt Cert can't create Wildcard-Cert using Cloudflare DNS

### ISSUE THREAD

**Issue by typoworx-de** [jc21/nginx-proxy-manager#628] opened 2020-10-05 07:42 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
Yes
- Are you sure you're not using someone else's docker image?
Yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?
Yes

**Describe the bug**
- A clear and concise description of what the bug is.
Tried to create wildcard-domain certificate using Letsencrypt + Cloudflare. This worked great for "regular" (non-wildcard) domains, but fails for something like "*.host.my-hosting-service.net".

I only get js-alert saying "Internal Error". Please also note my other ticket #627 that more verbose error-dialogs (modal dialogs would be great) will be a great improvement to figure out what the reason is for some issues.

- What version of Nginx Proxy Manager is reported on the login page?
v2.5.0

**To Reproduce**
Go to SSL and try to create a Letsencrypt + Cloudflare verification cert with wildcard in it. Don't forget to enter Cloudflare DNS API Token. My token is approved to work with regular domains.

**Expected behavior**
Rolling out the requested cert or telling me a more verbose error-message what's wrong behind.

**Screenshots**
![image](https://user-images.githubusercontent.com/1282298/95052344-0d98cc00-06ef-11eb-82f4-2a2e721785c0.png)

**Operating System**
Docker running on Ubuntu 20

**Additional context**

**Comment by dugaa95** [comment] 2020-10-08 15:54
I have same Problem

**Comment by chaptergy** [comment] 2020-11-06 11:38
This has most likely changed since #635, does this issue still persist or can it be closed?

**Comment by chris1668** [comment] 2020-12-19 06:38
An internal error still persists, I just tried to use Cloudflare DNS Challenge and it seems the Docker Image from JLesage does not have the Cloudflare-DNS module installed, so after running pip3 install certbot-dns-cloudflare==1.8.0
matching the version from the internal error message has now lead me to this Command Failed Error with no obvious reason standing out to me.
`Error: Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "npm-15" --agree-tos --email "" --domains "*.example.com" --authenticator dns-cloudflare --dns-cloudflare-credentials "/etc/letsencrypt/credentials/credentials-15"
Traceback (most recent call last):
File "/usr/bin/certbot", line 11, in
load_entry_point('certbot==1.4.0', 'console_scripts', 'certbot')()
File "/usr/lib/python3.8/site-packages/certbot/main.py", line 15, in main
return internal_main.main(cli_args)
File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1315, in main
log.pre_arg_parse_setup()
File "/usr/lib/python3.8/site-packages/certbot/_internal/log.py", line 55, in pre_arg_parse_setup
temp_handler = TempHandler()
File "/usr/lib/python3.8/site-packages/certbot/_internal/log.py", line 243, in init
stream = util.safe_open(self.path, mode='w', chmod=0o600)
File "/usr/lib/python3.8/site-packages/certbot/util.py", line 197, in safe_open
fd = filesystem.open(path, os.O_CREAT | os.O_EXCL | os.O_RDWR, *open_args)
File "/usr/lib/python3.8/site-packages/certbot/compat/filesystem.py", line 149, in open
return os.open(file_path, flags, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/tmpyp2bcu3c/log'

at ChildProcess.exithandler (child_process.js:303:12)
at ChildProcess.emit (events.js:315:20)
at maybeClose (internal/child_process.js:1021:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)`
![dns_challenege_error](https://user-images.githubusercontent.com/3466448/102682885-b2209b00-4181-11eb-8fd4-abbfc8dfa8a0.png)

**Comment by chaptergy** [comment] 2020-12-19 09:49
How did you install the proxy manager? It seems certbot wants to write to a log file inside the `/tmp` directory, been t has no permission to do so.

**Comment by chris1668** [comment] 2020-12-19 19:48
Its a Docker Container in Unraid with all the default file permissions and UID/GID, I can see the File permissions for the tmp directory is `d---------    1 app      users          0 Dec 19 11:38 tmpamks2ml4` not sure why that temp folder it generates  for the log has no write permissions as other app directories in /tmp do have write ie.`d-w-------    1 app      users          0 Dec 19 11:38 pip-req-tracker-0obopsdc`

**Comment by chaptergy** [comment] 2020-12-20 21:21
Unfortunately I am not able to reproduce your issue, not with the official docker image nor with the JLesage docker image. Could you provide the docker-compose file you use?

**Comment by chaptergy** [comment] 2021-05-10 17:06
I will now close this issue as there have not been any updates.

**Closed by chaptergy** 2021-05-10 17:06 UTC
Labels: bug
