### ISSUE TITLE
How to proxy/use multiple services under one address?

### ISSUE THREAD

**Issue by jakegibbonsdev** [jc21/nginx-proxy-manager#934] opened 2021-03-10 03:46 UTC
Simple services I can make work. How do I proxy an aliased service? 

From the project https://github.com/ubc/docker-canvas, I have implemented https://github.com/ubc/docker-canvas/blob/master/docker-compose.yml. The app service is anchored and the worker service is aliased. I have tried to proxy to the app service with container name port 80
the worker service with container name port 80
the app service with container name port 8900
the worker service with container name port 8902
the app service with container IP port 80
the worker service with container IP port 80

I have even tried to set a custom location for / to http://example.com:8900/login/canvas, but I keep getting "Congratulations You've successfully started the Nginx Proxy Manager..."

  app: &app
    image: docker-canvas
    build: .
    command: bash -c "./wait-for-it.sh -t 40 db:5432 && /usr/src/entrypoint"
    environment:
...
    ports:
      - "8900:80"
...
  worker:
    <<: *app
    command: bundle exec script/delayed_job run
    ports:
      - "8902:80"

**Comment by Val-istar-Guo** [comment] 2021-03-14 16:00
same problem

**Comment by hhyhxc** [comment] 2021-03-21 12:48
i have same problem.  help。。

**Comment by chaptergy** [comment] 2021-05-12 20:14
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/689

**Closed** 2021-05-12 20:16 UTC
