### ISSUE TITLE
The access list doesn't work if you use custom locations.

### ISSUE THREAD

**Issue by fischdenflo** [jc21/nginx-proxy-manager#743] opened 2020-11-28 00:53 UTC
Unfortunately the access list doesn't work if you use it like that.

_Originally posted by @fischdenflo in https://github.com/jc21/nginx-proxy-manager/issues/104#issuecomment-735018126_

**Comment by mochman** [comment] 2020-12-03 19:41
For a workaround, you can just add your access criteria to the custom location settings.  It has to be updated though, if you change the access list criteria.

**Comment by fischdenflo** [comment] 2020-12-03 19:44
Is it possible to give me an example? 🙈 But many thanks 🙏

**Comment by mochman** [comment] 2020-12-04 05:18
Sure.  This example only allows local IPs from 192.168.0.0 - 192.168.255.255 to have access.  
```
    # Access Rules
    allow 192.168.0.0/16;
    deny all;

    # Access checks must...
    satisfy all;
```
The way I got this was to make a fake proxy host with an access list I wanted to use.  Then I went into my `./data/nginx/proxy_host/` folder on my server.  There you will see a bunch of numbered .conf files.  Open the highest numbered one (the one just created).  In the 
```
location / {
``` 
section of that file, you should see a set of access rules that were made.  Just copy those into your actual custom locations.

**Comment by fischdenflo** [comment] 2020-12-04 11:02
Ok I will test ist. Many Thanks 🙏

**Comment by derekoharrow** [comment] 2020-12-14 16:55
I'm seeing the same behaviour - access lists seem to be ineffective if you have custom locations specified. This is quite a critical feature to be missing.

How can you setup user basic authentication with custom locations?

**Comment by mjeschar** [comment] 2021-01-19 21:20
Same issue here, 90% of my domains are using custom locations. I really need the working basic auth. for those services. Any chance to implement it? I really like the GUI!

**Comment by l4rm4nd** [comment] 2021-03-26 18:05
Custom locations will break any access lists. Further, the HTTP/2 SSL option can also break access lists.

If you need to habe custom locations, proceed as explained by @mochman. Configure your access rules specifically for each custom location entry.

**Comment by mcastorina** [comment] 2021-04-03 01:17
I think this is a pretty critical bug. The UI implies the access list is effective for the entire proxy host when it's not for custom locations.

**Comment by chaptergy** [comment] 2021-05-12 21:16
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/148

**Closed by chaptergy** 2021-05-12 21:16 UTC
