### ISSUE TITLE
Unable to connect to db

### ISSUE THREAD

**Issue by whisperdancer** [jc21/nginx-proxy-manager#483] opened 2020-06-30 17:28 UTC
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image? Yes
- Are you sure you're not using someone else's docker image? Yes
- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network? n/a

**Describe the bug**
- A clear and concise description of what the bug is.
I'm running on RaspPi 3B+. Just installed via your quick install. The install had no errors. The error log shows unable to connect to the db. I can get to the login page, but get bad gateway when entering credentials. No surprise since the image is running unhealthy due to the inability of a db connection.
- What version of Nginx Proxy Manager is reported on the login page? 2.3.1

**To Reproduce**
1. Go to '...' Just run docker compose with your quick install

**Expected behavior**
I expect it to work without errors. I expect it to connect to the db

**Operating System**
RaspPi 3B+ running latest version of RaspPi OS

**Additional context**
The log file just keeps showing this error. 
[6/30/2020] [5:15:19 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
[6/30/2020] [5:15:20 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
[6/30/2020] [5:15:21 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
[6/30/2020] [5:15:22 PM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db

**Comment by GEkuL** [comment] 2020-07-01 14:05
> **Describe the bug**
> 
>     * A clear and concise description of what the bug is.
>       I'm running on RaspPi 3B+. Just installed via your quick install. The install had no errors. The error log shows unable to connect to the db. I can get to the login page, but get bad gateway when entering credentials. No surprise since the image is running unhealthy due to the inability of a db connection.
> 
>     * What version of Nginx Proxy Manager is reported on the login page? 2.3.1
> 
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to '...' Just run docker compose with your quick install
> 
> 
> **Expected behavior**
> I expect it to work without errors. I expect it to connect to the db
> 
> **Operating System**
> RaspPi 3B+ running latest version of RaspPi OS


Hi
Sorry for quite stupid question, nevertheless, did you a have a firewall enabled on your RaspPi?

I think I had the same problem with the login to the Proxy Manager on the first page. The problem was solved by reinstalling the container.

**Comment by whisperdancer** [comment] 2020-07-02 19:16
No firewall. I"m just testing so installed Rasperry OS, docker and docker compose, then installed nginx proxy manager. Very clean system and get the errors.

**Comment by CoLdAs1cE** [comment] 2020-07-13 09:13
same here with me with and without firewall ;(

**Comment by CoLdAs1cE** [comment] 2020-07-13 09:25
did the same as @whisperdancer 
same here with me with enabled(with allowed port)/disabled firewall ;(

same error 
```

[7/13/2020] [9:12:12 AM] [Global   ] › ✖  error     connect EHOSTUNREACH 172.19.0.3:3306


[7/13/2020] [9:12:13 AM] [Global   ] › ✖  error     getaddrinfo ENOTFOUND db
```

getting this from db
(seems like db is build from 64 does not work with pi 4 ;( )
```
standard_init_linux.go:211: exec user process caused "exec format error"

```

**Comment by codeagencybe** [comment] 2020-09-19 12:40
I got it working!

`db_1 | 2020-09-19 12:31:16 0 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages!
`

All I did was delete the .ibdata1 file that shows 0kb
And then re-deploy the whole setup. Now it generates a new clean .ibdata file that is around 12Mb size

**Comment by jc21** [comment] 2021-02-08 01:51
Duplicate of #509 and should be fixed with latest mariadb-aria image.

**Closed by jc21** 2021-02-08 01:51 UTC
Labels: bug

**Comment by kautsaridris** [comment] 2022-01-01 05:36
hi @jc21 i am sorry if i create the question here, 
i want to know  if may to make connection to sql server (microsoft) using NPM ?

**Comment by chaptergy** [comment] 2022-01-01 15:56
@kautsaridris Please do not hijack issues with off topic questions. Tagging the owner / a maintainer when it is not because of a relevant reply but just so you are noticed is also not the way to go.

But to answer your question, no MSSQL is not supported. Currently only MySQL / MariaDB and SQLite is supported, and going forward MySQL / MariaDB support will be dropped in favor of the much less error prone SQLite (since it runs in the same container).

**Comment by operinko** [comment] 2022-01-01 18:14
Sorry for continuing a bit off-topic, but..
> and going forward MySQL / MariaDB support will be dropped in favor of the much less error prone SQLite (since it runs in the same container).
That's *terrible* news for any HA setups around there. It's practically impossible to get multiple instances of NPM to utilize a single SQLite DB without issues, so a slave-master DB setup is a must.

**Comment by LeehamElectronics** [comment] 2022-03-08 06:20
> I got it working!
> 
> `db_1 | 2020-09-19 12:31:16 0 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 768 pages, max 0 (relevant if non-zero) pages! `
> 
> All I did was delete the .ibdata1 file that shows 0kb And then re-deploy the whole setup. Now it generates a new clean .ibdata file that is around 12Mb size

Where is `ibdata1 `exactly?

**Comment by LeehamElectronics** [comment] 2022-03-08 06:25
So for some reason, when I restarted NPM I started getting this issue, I had a look at it and it had no networks assigned to it. It was working fine before, so it seems like, upon restarting the container, the container disconnected from the network it was assigned to. I simply added the network back to the containers and it works fine again... Strange.
