### ISSUE TITLE
SSL Cert / vhost naming in filesystem

### ISSUE THREAD

**Issue by osnet** [jc21/nginx-proxy-manager#761] opened 2020-12-06 17:52 UTC
If generating a SSL cert  it gets  stored  like  this

```
  ssl_certificate /etc/letsencrypt/live/npm-16/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-16/privkey.pem;
```

this is a little bit confusing. since i have to "extract" or copx the generated certs to  instances like  mailserver, gitlab etc.
Is there a way to geht them names correctly like the corresponding vhost ?

thx in advance

**Comment by osnet** [comment] 2020-12-06 18:45
or at least add a hint in the frontend  on every ssl host  which ID the cert has

**Comment by chaptergy** [comment] 2021-05-12 21:37
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/174

**Closed by chaptergy** 2021-05-12 21:37 UTC
Labels: enhancement
