### ISSUE TITLE
Access List in custom location

### ISSUE THREAD

**Issue by Patriciawa** [jc21/nginx-proxy-manager#459] opened 2020-06-11 15:05 UTC
**Is your feature request related to a problem? Please describe.**
Right now (as far as I can tell) you can't add an access list to a custom location, only the domain.

**Describe the solution you'd like**
A option to add an access list to the "Custom Locations" tab. This access list overrides the access list in the "Details" tab, or add an option to override it.

**Describe alternatives you've considered**
Manually editing the config.

**Comment by Patriciawa** [comment] 2020-06-11 15:47
I've also noticed that when you have a custom location, it won't force it to https when you have that option enabled in the ssl tab. So I went to the advanced tab and added the following;

```
location /customlocation/* {
         return 301 https://example.com$request_uri;
 }
```
The `*` means in this case that everything after /customlocation/ will be returned to https. Works like a charm!

**Comment by chaptergy** [comment] 2021-05-12 13:41
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/148

**Closed by chaptergy** 2021-05-12 13:41 UTC
Labels: enhancement
