### ISSUE TITLE
Make Web interface content (JS, CSS) use relative paths

### ISSUE THREAD

**Issue by bobland1** [jc21/nginx-proxy-manager#877] opened 2021-02-08 12:58 UTC
Hi, I am trying to hide the nginx proxy manager behind a sub directory. But sadly this is not possible due to the js and css being loaded in via absolute paths. Is there a way we can change this or a solution I can use to address this.

This is a duplicate of #631

On the other ticket I proved a somewhat fix using sub filters, sadly this did not resolve the full issue as although the redirects, css and javascript now load. The login doesn't work now.

Also, does my ticket relate at all to **`branch/static-content`**

**Comment by bobland1** [comment] 2021-02-08 13:02
Copying my comment from #631 

> proxy_set_header Accept-Encoding "";
> sub_filter 'href="/' 'href="/app/nginx/';
> sub_filter 'src="/' 'src="/app/nginx/';
> sub_filter 'window.location="/' 'window.location="/app/nginx/';
> sub_filter_once off;
> sub_filter_types text/css text/javascript;

I used the above to try and get the css / js to load on the page. Seems though the easiest way around this is to change all the absolute paths to relative paths. So I can use 

```
location /app/nginx/ {
    proxy_pass http://localhost:81/
}
```

**Comment by xannor** [comment] 2021-02-14 16:21
Looking at the code, and researching nodejs express, [this line](https://github.com/jc21/nginx-proxy-manager/blob/ea28da90b23d1896c3322d23897672fa2f20954a/backend/app.js#L55), sets the "prefix" to / so all routing will force things back to /. I believe the app operates relative, but the service forces hard paths. The solution I see would be to have some way for the service to be configured with a hard prefix instead of just / or for it to have some way to pass a trusted header (i.e. a header it is told to trust via config, becasue you really cannot trust any of them.)

**Comment by bobland1** [comment] 2021-02-18 20:25
@xannor Would this be a easy change I could do? Or would this be something which would require alot of work? If so I could bang in a PR with the change... unless you wanted to

**Comment by xannor** [comment] 2021-02-19 13:08
Some parts may be easy, I'm not sure about the client side. For the server side all I believe is needed is a small change to the app.js file: [app.use(require('config').prefix || '/', require('./routes/api/main'));](https://github.com/jc21/nginx-proxy-manager/blob/ea28da90b23d1896c3322d23897672fa2f20954a/backend/app.js#L55)

This would use a prefix property set in the config as the base prefix for the express engine, so all urls created would be relative to that point, and it should default to the original if not provided so it would break any existing setups. This approach is not very robust so it would be easy for someone to break their setup by putting bad data in the config, but this would be a more "advanced" usage.

For the client side it may be more complicated. All the points where the routing is hard coded to '/' (such as /api/, /js/, and /images/) would need to be converted to either get a prefix or path from the app router or from the server. I am less familiar with the client side framework so I am not sure if there is an easy way for that. Also all the html templates would need to either use relative or some form of passed in prefix since they have a lot of hard coded references. This believe is where most of the work would be needed.

**Comment by chaptergy** [comment] 2021-05-12 18:51
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/631

**Closed by chaptergy** 2021-05-12 18:51 UTC
Labels: enhancement
