### ISSUE TITLE
SSL Certificates tab not showing that certs are renewed

### ISSUE THREAD

**Issue by ghallford** [jc21/nginx-proxy-manager#1239] opened 2021-07-13 18:36 UTC
Running v2.9.4 on Unraid in Docker container. 

The SSL certificate tab is showing that all but 1 of my certificates has expired from Let's Encrypt but they are all renewing properly and they are not expired. 2 screenshots attached up showing expired in nginx-proxy-manager and the actual cert expiry

![Screenshot 2021-07-13 143508](https://user-images.githubusercontent.com/17805839/125506638-84be94b3-c020-4053-8321-1a0f08c155ef.png)

![Screenshot 2021-07-13 143428](https://user-images.githubusercontent.com/17805839/125506644-ac126fb1-c753-4270-b7b0-518db14ff342.png)

**Comment by chaptergy** [comment] 2021-07-13 18:51
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/792

**Closed by chaptergy** 2021-07-13 18:51 UTC
