### ISSUE TITLE
Is it possible to increase the number of IP's or Networks allowed in access lists. 

### ISSUE THREAD

**Issue by kleewyck** [jc21/nginx-proxy-manager#625] opened 2020-10-02 01:39 UTC
Currently in access lists there is only the ability to list 4 ips or networks. I'd like to be able to list considerably more. 

The Background for this is I have set up a proxy from Cloudflair and this works very very well. So well in fact I would like to restrict my nginx server to only allow connections from Cloudflair. With the Cloudflair proxy enabled there is no need for other ips to connect to the server. This would greatly enhance the security of my site as no stray ip's could connect to it. The issue here is on Cloudflair's site they publish about 17 address ranges for IPv4 and several for IPv6 so I can't add all the ranges in. 

The ability to extend that access list would make  it even more useful.

**Comment by crgreenwood** [comment] 2020-10-02 17:17
I have exactly the same issue and came here looking to see if I could concatenate multiple networks on a single line. It sounds like I also need this enhancement.

**Comment by cbruscato** [comment] 2020-10-11 21:00
This is duplicate of my enhancement request #615

**Comment by camlafit** [comment] 2020-10-29 13:53
Hello

Here at office we are same problem. We need to allow different remote users to our internal service. 
4 ip range is not enough in this case.
Could be very nice to improve this behavior and allow without any restricted list.

**Comment by matt-cylanda** [comment] 2021-04-03 09:24
we need this as well

**Comment by chaptergy** [comment] 2021-05-12 18:47
Closed via https://github.com/jc21/nginx-proxy-manager/pull/975

**Closed by chaptergy** 2021-05-12 18:47 UTC
Labels: enhancement
