### ISSUE TITLE
Error popup when routing nginx container itself- Expectation Failed

### ISSUE THREAD

**Issue by CXZ7720** [jc21/nginx-proxy-manager#214] opened 2019-10-21 10:39 UTC
**Checklist**
[v] Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
[v] Are you sure you're not using someone else's docker image?
[v] If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
When I try to delete user, the alert message popups and it says **Expectation Failed**

**To Reproduce**
0. Proxy Nginx Container itself to subdomain : `nginx.example.com` and access through the domain.
1. Go to 'Users' tab
2. Click on menu button with 3 dots at the right end of each rows.
3. Click "Delete 'USERNAME' "
4. When modal pops, Click "Yse, I'm Sure" button. 
5. See error

Similar error popup shows in deleting proxy rules, 404 rules, etc.
**Expected behavior**
Delete users

**Screenshots**
![nginx](https://user-images.githubusercontent.com/29659112/67198703-79c8e400-f43a-11e9-9c04-250a69248e1b.png)

**Operating System**
Ubuntu 18.04 LTS,
AMD 2700X, DDR4 32GB
Nginx Proxy Manager v2.0.14

**Additional context**
Docker version 19.03.3, build a872fc2f86
User Agent Strings : 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.89 Safari/537.36

**Comment by chaptergy** [comment] 2021-05-11 17:58
As this issue is very old and I can't reproduce it, I will close this.

**Closed by chaptergy** 2021-05-11 17:58 UTC
Labels: bug
