### ISSUE TITLE
npinxpm container unhealthy when stopped container name used in host config

### ISSUE THREAD

**Issue by jacgl** [jc21/nginx-proxy-manager#1187] opened 2021-06-18 14:02 UTC
Hi,
I am using nginxpm to redirect traffic to another containers in docker, and typically I use container name instead of direct ip address. It works perfectly unless all containers are healthy.
BUT, when you restart docker and at least 1 container is not, nginxpm has the issue with start as well. Moreover, there is no access to web page, so no chance to even disable problematic container. In the log something like the line below can be found:

nginx: [emerg] host not found in upstream "mpd_mpc" in /data/nginx/proxy_host/21.conf:47,

(this is case when mpd_mpc is used in custom locations, but I believe the similar situation exists for "forward hostname")

Regards.

**Comment by chaptergy** [comment] 2021-06-18 14:21
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/633

**Closed by chaptergy** 2021-06-18 14:21 UTC
Labels: bug
