### ISSUE TITLE
Admin panel served at port 81 with no SSL at all?

### ISSUE THREAD

**Issue by hartwork** [jc21/nginx-proxy-manager#481] opened 2020-06-27 23:44 UTC
Hi!

The docs seem to [suggest serving the admin panel with no SSL on port 81](https://nginxproxymanager.com/setup/#running-the-app) and there is no mention of a threat model or security consequences. That seems like a troublesome choice for security, not just for people hosting at home. I have just seen a publicly accessible setup that has the log-in form send username and password unencrypted through the internet. Am I missing something?

Thanks and best, Sebastian

**Comment by jc21** [comment] 2020-06-27 23:50
The point of this project is to allow you to create your own SSL encrypted domains for any services, including NPM. So yes you can create your own `npm.yourdomain.com` pointing to NPM with hostname `127.0.0.1` and port `81`. Then if you really want your home-only network to be 120% secure, modify the docker-compose file and remove port 81 from the ports list.

**Comment by hartwork** [comment] 2020-06-28 00:01
Is it possible to serve the admin panel through SSL and is there documentation on that?

**Comment by bradyemerson** [comment] 2020-07-23 01:27
Based on the configuration options present today, no.  You can modify this file https://github.com/jc21/nginx-proxy-manager/blob/master/docker/rootfs/etc/nginx/conf.d/production.conf and create your own docker image with SSL enabled.  You'll also need to modify the curl health check to use https and ignore certificate errors.

It is common practice when using Docker reverse proxies that the SSL offloading is done at the nginx layer.  In almost all cases that I have seen, the internal communication between docker containers is done via plain transmission so that certificates don't have to be managed individually within each application.

As the maintainer said, the purpose of this application is to create reverse proxies with SSL support.  So it makes sense to leverage npm to create an admin reverse proxy for port 81 rather than creating a separate set of configuration options.  This way the configuration and SSL management is done in the same interface and with the same patterns as all of your other vhosts.

**Comment by bradyemerson** [comment] 2020-07-30 21:09
I'm not clear on the question.  This tool only manages vhosts, not the underlying docker applications.  If you're asking how to create a vhost with SSL, it's on the SSL tab in the editor.

**Comment by chaptergy** [comment] 2021-05-12 14:22
Closing as a duplicate of https://github.com/jc21/nginx-proxy-manager/issues/182

**Closed by chaptergy** 2021-05-12 14:22 UTC
Labels: bug
