### ISSUE TITLE
SSL certificates page lists some certificates as expired

### ISSUE THREAD

**Issue by nathcoad** [jc21/nginx-proxy-manager#1150] opened 2021-06-03 22:45 UTC
**Describe the bug**
Just upgraded docker image from 2.7.1 to the latest (docker-compose pull; docker-compose down; docker-compose up -d).
When logging in I notice the SSL certificates page lists a number of certificates as expired, with an expiry date in the past. However, running certbot renew inside the image shows that the certificates are not due for renewal, and I have confirmed that the sites proxied have valid certificates that expire in the future.

**Nginx Proxy Manager Version**
2.9.3

**To Reproduce**
1. Go to SSL Certificates page
2. See certificates listed as expired
3. Run "docker exec -it nginx-proxy-manager_app_1 certbot renew"
4. See output processing all npm-N.conf files and indicating that the certificates are not due for renewal yet

**Expected behavior**
SSL Certificates page should match certbot renew command

**Screenshots**

**Operating System**
Ubuntu 18.04.5 LTS

**Additional context**
$  docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:59 2020
 OS/Arch:           linux/amd64
 Experimental:      false

docker-compose.yml file:

version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # These are the settings to access your db
      # DB_MYSQL_HOST: "db"
      # DB_MYSQL_PORT: 3306
      # DB_MYSQL_USER: "npm"
      # DB_MYSQL_PASSWORD: "npm"
      # DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - reverseproxy-nw

networks:
    reverseproxy-nw:
        external: true

**Comment by chaptergy** [comment] 2021-06-04 08:17
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/792

**Closed by chaptergy** 2021-06-04 08:17 UTC
Labels: bug
