### ISSUE TITLE
Custom Location fails on second, third,...

### ISSUE THREAD

**Issue by tonydm** [jc21/nginx-proxy-manager#760] opened 2020-12-05 19:59 UTC
Great project, nice interface and function, thank you!

I have a single proxy host domain configured with two custom locations, aka /path(s).  The first path works/is redirected as expected.  The second, third, ... return a 404.  I've included my docker-compose.yml, ./data/nginx/proxy_host/1.conf snippet, and screenshots.

I'm not sure what it is I might be missing in the configuration or if indeed it's a bug.  I'm a little unclear on the `Use 1.1.1.1/path for sub-folder forwarding` statement under the /path field.  Obviously your wouldn't use 1.1.1.1, or other DNS.  I tried using the subdomain.domain.com but that failed as I would have expected since it would create a loop.  I'm also a little confused on the destination port setting of the proxy host since I'm redirecting using a custom location/path.  No port setting I've tried resolves the issue and no port is not an option as it's required. 

Thank you

**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
**YES**
```
version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      # Make sure this config.json file exists as per instructions above:
      - ${USERDIR}/nginx_proxy_manager/config.json:/app/config/production.json
      - ${USERDIR}/nginx_proxy_manager/data:/data
      - ${USERDIR}/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <obfuscated>
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'ngx_user'
      MYSQL_PASSWORD: <obfuscated>
    volumes:
      - ${USERDIR}/nginx_proxy_manager/data/mysql:/var/lib/mysql
```
- Are you sure you're not using someone else's docker image?
**YES**

- If having problems with Lets Encrypt, have you made absolutely sure your site is accessible from outside of your network?

**Describe the bug**
The first custom location works as expected.  The second, third, ... fail with a 404

- What version of Nginx Proxy Manager is reported on the login page?
**2.7.1**

**To Reproduce**
1. Enter a custom location for a domain
2. Navigate to the "custom location" aka /path in my browser's address bar
3. See the 404 error

**Expected behavior**
1. After creating the Custom Location navigating to custom location, aka /path and have page displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/1261605/101262062-0b57eb80-36f9-11eb-8906-477244e13b5e.png)

![image](https://user-images.githubusercontent.com/1261605/101262067-0eeb7280-36f9-11eb-88ed-8058b57aed04.png)
![image](https://user-images.githubusercontent.com/1261605/101261519-2de80580-36f5-11eb-881a-cae4d32b0160.png)
![image](https://user-images.githubusercontent.com/1261605/101261582-b49ce280-36f5-11eb-8949-d98ab6a82a3c.png)
![image](https://user-images.githubusercontent.com/1261605/101261752-c92daa80-36f6-11eb-9dee-d68caca2cec5.png)
![image](https://user-images.githubusercontent.com/1261605/101261522-33455000-36f5-11eb-8b26-90fc768ea6bc.png)
![image](https://user-images.githubusercontent.com/1261605/101261525-36d8d700-36f5-11eb-9942-7fc61ef4f129.png)
![image](https://user-images.githubusercontent.com/1261605/101261757-d0ed4f00-36f6-11eb-91e6-dad72f8934d2.png)
![image](https://user-images.githubusercontent.com/1261605/101262657-92a75e00-36fd-11eb-8e14-a46e2bcc9d5d.png)

### snippet from ./data/nginx/proxy_host/1.conf
```
#...
  location /smokeping {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_pass       http://10.10.0.173:9001;

  }

  location /dockerui {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_pass       http://10.10.0.173:9000;
    
  }
#...
```

**Operating System**
Ubuntu 20.04.1
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.27.4
HP Elite 8300  i5-3470S, 16GB Ram, 1TB SSD

### ./data/logs/proxy_host-1.log
```
[05/Dec/2020:20:17:33 +0000] - 404 404 - GET https <obfuscated>.com "/dockerui" [Client 10.10.0.1] [Length 19] [Gzip -] [Sent-to 10.10.0.173] "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36" "-"
```
No relative info from 
```
data/logs/error.log
data/logs/default_host.log
data/logs/default.log
```

**Comment by tonydm** [comment] 2020-12-10 00:49
Hello again, I know it's going into the holidays and lives are anything but normal.  Just wondering if there's any idea what might be going on to cause this custom location issue.

Thanks again

**Comment by NightFalcon650** [comment] 2020-12-12 22:09
i got have the same problem. :-(

**Comment by tonydm** [comment] 2020-12-12 22:45
@NightFalcon650 

I went ahead and moved on to another solution but I wanted to allow time for a response and perhaps a fix.  The team has put a lot of time and effort into this project and I really like the simple yet functional web interface.  It really is a nice solution.  I don't want to be ungrateful or dismiss the effort put into the project.  But I couldn't wait and since there's been no response thus fat I had to find another.  My solution does require a little bit more manual work but it works well and gives me the Letsencrypt certs with the custom path support.  One thing to note, however.  I found that in some cases that the custom path doesn't work with certain websites which are proxied.  Home Assistant is one.  You don't get a 404, but the page doesn't fully load.  A little research revealed that it's a known issue.  Unifi Controller was another one that wouldn't proxy to a custom path.  I had preferred custom paths over subdomains for the additional security if one were to scan DNS for a given domain.  But I found that it's pretty difficult getting subdomain information from NS servers.  In any case, I'd love to return to this project if/when a resolution is found.  If you'd like to know the direction I went IM me.

Best

**Comment by pmoya-in-the-web** [comment] 2020-12-26 13:41
i am also experiencing the same problem.

**Comment by mossaab** [comment] 2020-12-29 02:29
Replace the IP address 10.10.0.173 in the custom location by the hostname ( in your case must be the service name)
ig : 
http  :  smokeping   : 9001
http :  dockerui  :  9000

**Comment by chaptergy** [comment] 2021-05-12 21:35
This is more of an nginx thing, see [here](https://serverfault.com/questions/376162/how-can-i-create-a-location-in-nginx-that-works-with-and-without-a-trailing-slas) or [this](https://serverfault.com/questions/792326/nginx-proxy-pass-using-subfolder). You can also define `location` blocks in the advanced tab, since the text on there will be inserted within the `server` block.

As this is not really related to NPM, I will close this.

**Closed by chaptergy** 2021-05-12 21:35 UTC
Labels: bug

**Comment by tablatronix** [comment] 2021-09-26 02:33
Same issue, not sure I understand what the issue is and why I can't do this.. or what those links reference, it seems to just be people that don't know how to use regex..

Am I missing some obvious answer here?

**Comment by federicoalvarez-github** [comment] 2022-03-10 13:25
Why NGINX/NPM are so troublesome clearly goes over my head. I wished by 2022 we already had a simple way to route ip/ports.

**Comment by JBlond** [comment] 2022-08-10 10:09
@federicoalvarez-github What works is 

Edit proxy host -> Advanced -> Custom Nginx Configuration

```nginx
location /dockerui/ {
    rewrite /dockerui/(.*) /$1  break;
    proxy_pass  http://10.10.0.173:9000;
}

location / {
    # Proxy!
    include conf.d/include/proxy.conf;
}

**Comment by dmr138** [comment] 2022-10-30 18:35
> @federicoalvarez-github What works is
> 
> Edit proxy host -> Advanced -> Custom Nginx Configuration
> 
> ```nginx
> location /dockerui/ {
>     rewrite /dockerui/(.*) /$1  break;
>     proxy_pass  http://10.10.0.173:9000;
> }
> 
> location / {
>     # Proxy!
>     include conf.d/include/proxy.conf;
> }
> ```

!! Thank you after many hours of searching/ trial and error this worked for me. Hopefully I can use this for other services where I cant modify the url base (maybe home-assistant)

**Comment by tablatronix** [comment] 2022-10-30 20:18
So the final answer is NPM UI cannot create these rules it seems, so custom locations cannot apply to ports without custom rules

**Comment by JBlond** [comment] 2022-10-30 20:48
> So the final answer is NPM UI cannot create these rules it seems, so custom locations cannot apply to ports without custom rules for nginx. Isnt the whole point of this app to create rules for you though?

Indeed the UI can't do this, even though IMHO it should.

**Comment by dmr138** [comment] 2022-10-30 20:58
adding the above mentioned code to the advanced tab add this to my config
`location /portainer/ {`
`rewrite /portainer/(.*) /$1  break;`
`proxy_pass  https://192.168.1.6:9443;`
`}`


From custom locations ui set the path as `/portainer/` and fill in the rest like you normally would. then click the gear icon and in the custom section add `  rewrite /dockerui/(.*) /$1  break;`. 

that might do the trick without needing to use the advanced tab and should add the same thing to your config as listed above but I have not tested this yet.

(I did not use the `location / {
    # Proxy!
    include conf.d/include/proxy.conf` line as I already had that location block in my config file.)

**Comment by iJokerboy** [comment] 2023-02-17 00:25
If ther is anyone as noob as me:
you are going to make changes inside ngix proxy manager website
go to the proxy hosts page and click on the 3 dot thing on the site of your host, there are 5 tabs, go to the advanced tab and paste what the masters gave us above:

location /portainer/ {
rewrite /portainer/(.*) /$1  break;
proxy_pass  https://192.168.1.6:9443;
}


change the names "portainer" to the app you want to add and the ip/port to the one assigned to the app you want to use

save and be happy.

REMEMBER, DON'T BE DUMB LIKE ME AND DON'T ADD THE SAME THING ON CUSTOM LOCATIONS TAB... KEEP IT EMPTY

**Comment by Suryah07** [comment] 2023-06-17 13:04
My domain is example.com and i access my app through example.com/app1 and whenever i click on a link through my app it goes to the link example.com/login.html instead of example.com/app1/login.html.
Config : 

location /app1/ {
rewrite /app1/(.*) /$1 break;
proxy_pass http://192.168.x.x:80;
}

**Comment by jucajuca** [comment] 2023-08-29 09:59
> So the final answer is NPM UI cannot create these rules it seems, so custom locations cannot apply to ports without custom rules for nginx. Isnt the whole point of this app to create rules for you though?

[chaptergy](https://github.com/chaptergy) it seems to me that npm should be able to do this thing, or at least give warning. I just wasted a lot of time trying to figure out why is this not working. Any comments on this?

**Comment by alrepin** [comment] 2024-01-16 22:35
location /portainer/ {
rewrite /portainer/(.*) /$1  break;
proxy_pass  https://192.168.1.6:9443;
} not work for me((

**Comment by ashe0047** [comment] 2024-05-11 05:59
> location /portainer/ { rewrite /portainer/(.*) /$1 break; proxy_pass https://192.168.1.6:9443; } not work for me((

Sama here, did something change? this doesnt work on the latest NPM

**Comment by dmr138** [comment] 2024-05-11 21:41
Try replacing 192.168.1.6 with the local IP of your machine running portainer.

**Comment by azrulasree** [comment] 2024-06-26 05:20
working for me.

location /myapp/ {
rewrite /myapp/(.*) /$1 break;
proxy_pass HTTP://192.168.1.6:8081/;
}

**Comment by mcrook587** [comment] 2025-04-15 06:44
STILL NOT WORKING IN 2025. FIX YOUR SHIT! OVER THE BS!!!! LIKE EVERYONE, MOVING ON TO A BETTER PROJECT!

cant wait for this trash app the end up in the landfill. now in the process of moving to a different proxy manager.

THANKS FOR THIS SHIT PROJECT!
