### ISSUE TITLE
Applying a Basic Authentication policy against a reverse proxy to the management interface creates authentication loop

### ISSUE THREAD

**Issue by 1h8fulkat** [jc21/nginx-proxy-manager#719] opened 2020-11-13 20:39 UTC
When you setup a reverse proxy to the NGINX Proxy Manager host IP, and enable an authentication policy, it loops through the authentication prompt never allowing you to access the management interface.

**To Reproduce**
Create a reverse proxy to the host IP on the NGINX Proxy Manager port and enable an authentication policy

**Expected behavior**
A Basic authentication prompt followed by the NGINX Proxy Manager login screen.

**Operating System**
Office Docker Container on Ubuntu 16.04

**Comment by jmllubes** [comment] 2020-11-15 22:20
Same here, but with Oracle OS.

**Comment by jmllubes** [comment] 2020-11-16 21:10
I resolved activating 
![image](https://user-images.githubusercontent.com/16512469/99308636-8a73a580-2858-11eb-85e9-533db54147d2.png)

**Comment by 1h8fulkat** [comment] 2020-11-17 19:52
> I resolved activating
> ![image](https://user-images.githubusercontent.com/16512469/99308636-8a73a580-2858-11eb-85e9-533db54147d2.png)

Unfortunately, this does not solve my issue.

**Comment by jmllubes** [comment] 2020-11-21 18:37
I solved deleting all images , containers , volumes and configuration files and directory. I  mount all in docker compose like the new [setup](https://nginxproxymanager.com/setup/) and now all is ok.

**Comment by 3xitsharp** [comment] 2020-12-27 20:29
> I solved deleting all images , containers , volumes and configuration files and directory. I mount all in docker compose like the new [setup](https://nginxproxymanager.com/setup/) and now all is ok.

I tried this but get the same issue as OP.

Access List with:
Satisfy Any
Pass Auth to Host(on and off)
Auth with test:test and same username:password as admin account

**Comment by parasdaryanani** [comment] 2021-04-03 19:02
I'm facing this issue as well. Not only does it not allow you to access the NPM login screen, it also keeps asking for login when trying to access any proxy host. For redirection hosts, it lets you login just fine for some reason.

**Comment by chaptergy** [comment] 2021-05-12 20:54
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/334

**Closed by chaptergy** 2021-05-12 20:54 UTC
Labels: bug
