### ISSUE TITLE
With version 2.9.13 it is not possible to add custom certificates

### ISSUE THREAD

**Issue by IT-Bachmann** [jc21/nginx-proxy-manager#1729] opened 2022-01-04 23:28 UTC
With version 2.9.13 & 14 it is not possible to add custom certificates. Nothing happens when you click the button in the SSL tab

**Comment by chaptergy** [comment] 2022-01-04 23:56
Please use the search before opening issues. Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1676, https://github.com/jc21/nginx-proxy-manager/issues/1693, https://github.com/jc21/nginx-proxy-manager/issues/1700 and https://github.com/jc21/nginx-proxy-manager/issues/1707.

Though this issue was fixed in 2.9.14. Your browser probably still serves you the cached version of the website which still contains the bug. Make sure to clear your browsers cache and try again.

**Closed by chaptergy** 2022-01-04 23:56 UTC
Labels: bug
