### ISSUE TITLE
strip preceding and following spaces from IP address entries

### ISSUE THREAD

**Issue by binarytide** [jc21/nginx-proxy-manager#1043] opened 2021-04-27 17:58 UTC
**Is your feature request related to a problem? Please describe.**
sometimes when copying in an IP address it make include a space in front of the address and create a scenario where things look right but routing doesn't work properly

**Describe the solution you'd like**
strip preceding and following spaces from IP address entries

**Describe alternatives you've considered**
warn users of spaces in entry. currently there is no feedback when a user accidentally adds an entry with a space and it will have adverse affects on routing(doesn't work at all)

**Additional context**
none that I can think of

**Comment by chaptergy** [comment] 2021-05-12 23:36
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/783

**Closed by chaptergy** 2021-05-12 23:36 UTC
Labels: enhancement
