### ISSUE TITLE
OpenID Connect with Proxy Manager

### ISSUE THREAD

**Issue by mhankosky** [jc21/nginx-proxy-manager#888] opened 2021-02-12 02:31 UTC
Hi,

I would like to see support added for OpenID Connect (OAuth 2.0) in nginx proxy manager. 

NGINX supports this -> https://github.com/nginxinc/nginx-openid-connect

But it would be nice to be able to add authentication providers and assign them to sites.

This way you can protect legacy web apps.

**Comment by mosaati** [comment] 2021-03-22 08:25
There is a great tutorial done by IBRACORP on YouTube using Authelia. https://www.youtube.com/watch?v=fr-t7sGrYtI.

Hope this helps.

**Comment by chaptergy** [comment] 2021-05-12 23:14
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/437

**Closed by chaptergy** 2021-05-12 23:14 UTC
Labels: enhancement
