### ISSUE TITLE
Import/Export/Backup Configuration via GUI

### ISSUE THREAD

**Issue by Jiriteach** [jc21/nginx-proxy-manager#1197] opened 2021-06-21 23:51 UTC
Feature request that allows exporting of configuration via the GUI. This would make life easier to quicky backup lots of config.

Thanks

**Comment by chaptergy** [comment] 2021-06-23 07:12
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/168

**Closed by chaptergy** 2021-06-23 07:12 UTC
Labels: enhancement
