### ISSUE TITLE
[Request] Default DNS Challenge Credentials

### ISSUE THREAD

**Issue by SS-G-SS** [jc21/nginx-proxy-manager#1167] opened 2021-06-10 02:57 UTC
Instead of writing the same DNS Challenge credentials over and over. A default credentials for DNS Challenge will be great and helpful when adding a new subdomains.

**Comment by chaptergy** [comment] 2021-06-10 06:35
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/1093

**Closed by chaptergy** 2021-06-10 06:35 UTC
Labels: enhancement
