### ISSUE TITLE
Certbot outdate version errros

### ISSUE THREAD

**Issue by vncloudsco** [jc21/nginx-proxy-manager#1075] opened 2021-05-07 04:52 UTC
We tried to install ssl for our domain and failed. can you check for us? How can I update it?

pkg_resources.VersionConflict: (certbot 0.31.0 (/usr/lib/python3/dist-packages), Requirement.parse('certbot>=1.1.0'))
Please see the logfile '/tmp/tmpf5ym37j6' for more details.

**Comment by jc21** [comment] 2021-05-07 04:57
Duplicate of #1065

**Closed by jc21** 2021-05-07 04:57 UTC
Labels: bug
