### ISSUE TITLE
Tags and Filters

### ISSUE THREAD

**Issue by Jonakss** [jc21/nginx-proxy-manager#1615] opened 2021-11-29 15:51 UTC
**Is your feature request related to a problem? Please describe.**
When you have starting to have several Proxies hosts configured for example, can be a little messy to 
I've many Proxy Hosts configured, I can't filter neither group them. This can make things easier while editing some records or 

**Describe the solution you'd like**
Implement a tag system, where we can filter, for example Production, Staging, Monitoring, Infrastructure and so on.
In addition the possibility to filter the groups, status, etc.
This could be implemented in the Header with a search box for the Tags, and a Drop-down in the Titles.
![image](https://user-images.githubusercontent.com/11493034/143899330-e1ab071a-2fc1-4e60-a46b-cefe37537fb7.png)

**Describe alternatives you've considered**
No, Just search in the bast list.

**Additional context**
---

**Comment by chaptergy** [comment] 2021-11-29 16:03
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/409

**Closed by chaptergy** 2021-11-29 16:03 UTC
Labels: enhancement

**Comment by Jonakss** [comment] 2021-11-29 16:44
Sorry, I did a little search but I didn't see it.

Thanks, regards.
