### ISSUE TITLE
Default site certificate

### ISSUE THREAD

**Issue by poiNt3D** [jc21/nginx-proxy-manager#1145] opened 2021-06-02 15:45 UTC
Since wildcard certificates are supported, and there is a Default Site that Nginx points to,
it would be logical to make possible to assign a certificate to it. Right now Nginx Proxy Manager assigns "dummycert".

**Is your feature request related to a problem? Please describe.**
Every unknown subdomain greets me with threatening SSL error. 

**Describe the solution you'd like**
An option to set a default certificate.

**Describe alternatives you've considered**
I've been able to configure default_host/site.conf manually, but it's not very elegant solution.

**Comment by chaptergy** [comment] 2021-06-02 21:51
Duplicate of https://github.com/jc21/nginx-proxy-manager/issues/422

**Closed by chaptergy** 2021-06-02 21:51 UTC
Labels: enhancement
