### ISSUE TITLE
re: Dark theme

### ISSUE THREAD

**Issue by f3bandit** [jc21/nginx-proxy-manager#1205] opened 2021-06-25 09:58 UTC
**Is your feature request related to a problem? Please describe.**

Yes me and golem here don't like the bright lights

**Describe the solution you'd like**

If you could add a dark theme for us dungeon trolls that despise all that is bright
please and thank you! 

**Additional context**
yes you are awesome as well as you app! :) thx

**Comment by root9191** [comment] 2021-07-14 02:11
Totally Agree with that!

**Comment by frisodubach** [comment] 2021-07-19 16:28
Might be cool if we got the option to upload custom css instead.

**Comment by JesseyWhite** [comment] 2021-08-20 05:51
duplicate of https://github.com/jc21/nginx-proxy-manager/issues/707

**Comment by geekedtv** [comment] 2021-12-17 12:23
I second this. I am in this panel everyday and a dark theme would be an absolute game changer!

**Comment by chaptergy** [comment] 2021-12-17 12:31
Closing in favor of https://github.com/jc21/nginx-proxy-manager/issues/707

**Closed by chaptergy** 2021-12-17 12:31 UTC
Labels: enhancement
